### ISSUE TITLE
Single article gets displayed multiple times

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#135] opened 2016-06-15 21:26 UTC
![feedreader_003](https://cloud.githubusercontent.com/assets/10520767/16097756/d599c4ac-334f-11e6-8636-53da0e82dc74.png)

This is the console output:
http://pastebin.com/c8HpJA60

**Comment by jangernert** [comment] 2016-06-16 00:01
Again the updateArticleList function gets fired like a million times.
What distirbution/version of gnome are you on?
Also can you export your feeds as OPML? Maybe I can reproduce the issues somehow.

**Comment by fb87** [comment] 2016-06-16 10:09
Fedora 24 with Gnome 3.20. I'll look after OPML tomorrow.

**Comment by fb87** [comment] 2016-06-17 19:18
No idea how I can export my feeds.

**Comment by jangernert** [comment] 2016-06-17 19:24
On rhe feedly website there is a option somewhere to export as opml. Google can help.

**Comment by fb87** [comment] 2016-06-17 20:07
Thought export inside FR... here is it:
[feedly.opml.tar.gz](https://github.com/jangernert/FeedReader/files/321198/feedly.opml.tar.gz)

**Comment by jangernert** [comment] 2016-06-17 23:52
Thx, I'll try to set up a vm with fedora 24 and see if I can reproduce the bug with your feeds.

**Comment by fb87** [comment] 2016-06-18 13:21
Thanks! Next week F24 is officially out and I receive all the new updates, maybe it will get better then if it's related to something other.

**Comment by jangernert** [comment] 2016-06-18 15:19
Good News. I can reproduce the issue. Well, not this issue in particular, but the "updateArticleList"-spam. And I'm pretty sure this is what is causing most of your problems. I hope I can track down the issue soon ;)

**Comment by fb87** [comment] 2016-06-18 20:36
Nice. Sorry for the other PRs, I haven't had the feeling that they were related to each other...

**Comment by jangernert** [comment] 2016-06-18 21:35
Maybe I'm wrong and they aren't related after all. But even then there will be still time to report each and every one after this one is fixed.

**Comment by jangernert** [comment] 2016-06-18 23:13
Okay, I fixed the issue where the UI would get updated way too often during sync with back-ends other than tt-rss (that is why I never noticed). This does not directly fix any of your issues. But hopefully some of them will disappear because of this anyway.
At least this should make it easier to debug anything since the logs are not spammed by thousands of update messages.
Can you build git-master from source and test again?
I had to install the following packages on a fresh fedora 24 to compile FeedReader successfully:

> - gcc-c++
- vala
- vala-tools
- libgee-devel
- libsecret-devel
- libnotify-devel
- libsqlite3x-devel
- rest-devel
- webkitgtk4-devel
- libxml2-devel
- json-glib-devel
- gtk3-devel

**Comment by fb87** [comment] 2016-06-19 13:20
Ok, I did. After starting the program and clicking sync, the whole database seemed to be being processed somehow, which took about 10 minutes and produced ginormous output („Grabber: xyz“) which even exceeded the 10.000 lines buffer of my terminal. But a second sync was done with a couple of lines output.

**Comment by jangernert** [comment] 2016-06-19 13:28
Maybe a lot of new articles that were added during the sync? Grabber is responsible for grabbing the full html-content of articles that were synced and have a grabber-config-file available. And yes, the grabber produces quite some debug output, so if a lot of articles are being downloaded, this could happen. At least that would make sense.
Did you test if with the new version your reported issues are still present?

**Comment by fb87** [comment] 2016-06-19 13:37
Just 25 articles were new. I think the amount of time could be significantly reduced by creating worker threads and letting them do the grabs in parallel since it appears to be currently done by a single thread which has to wait most of the time.

The issues I reported occurred spontaneously, I will report further misbehaviour.

**Comment by jangernert** [comment] 2016-06-19 13:48
Then how should I know when issues are resolved and can be closed? :P

**Comment by fb87** [comment] 2016-06-19 13:50
I sadly don't know how to reproduce them, but I'll keep playing around and see what I can do.

**Comment by fb87** [comment] 2016-06-21 19:44
Now after reading/skipping about 15 of 150 new articles, I just got this screen:
![feedreader_003](https://cloud.githubusercontent.com/assets/10520767/16243504/dd5c1c1a-37f7-11e6-8e87-75a0dda5ba2d.png)

All feeds and articles were dropped even when restarting FR and the daemon. I just installed your new version and syncing now brought the feeds back on the left pane. So I assume the whole DB got deleted (but I don't know if it's due to the upgrade or due to the described bug).

**Comment by fb87** [comment] 2016-06-21 21:48
I encountered another bug: The read-status of articles gets lost while sync is active. Just read some articles while the program is syncing – when the sync is finished, the now read articles get displayed as unread again.

**Comment by jangernert** [comment] 2016-06-21 21:55
Well, the back-end sends me the state of the article as they were at the point of the request. If you modify the local state in the time between the request was made and the data gets written to the db of course the state will be overwritten. I can maybe update the state a little earlier (so the time-frame to trigger this gets smaller), but I can't avoid this problem completely.

**Comment by fb87** [comment] 2016-06-21 22:03
Can't the backend just add new ones without modifying already existing ones? Or can you collect the differences between sync start and sync end and apply them to the new table?

**Comment by jangernert** [comment] 2016-06-21 22:08
No, I need to get the states of (in theory all) articles in case they were read on another device or in the browser, or maybe were read in FeedReader and then later marked as unread again somewhere else (to remember to read the article later or something).

**Comment by jangernert** [comment] 2016-06-21 22:27
I will see if I can somehow reuse the code of the "offline-actions" for collecting actions during sync and performing them later. If not, this seems like a lot of work for little benefit.

**Comment by fb87** [comment] 2016-06-28 20:51
Now i read an article and meanwhile some new ones arrived. First the feed overview was cleared, after switching to „all“ and then „unread“ again, everything disappeared again and the whole database obviously was deleted again. Here are the first hundred lines of output after restarting the program and the corresponding daemon, maybe it helps: 

[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 1.6 beta
[ INFO  ] FeedReader: start daemon
[ ERROR ] CREATE VIRTUAL TABLE fts_table USING fts4 (content='articles', articleID, preview, title, author)
[ ERROR ] table fts_table already exists
[ INFO  ] Everything is logged. Used to debug!
[ ERROR ] CREATE VIRTUAL TABLE fts_table USING fts4 (content='articles', articleID, preview, title, author)
[ ERROR ] table fts_table already exists
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 1.6 beta
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] FeedServer: new with type 1
[ DEBUG ] Ping: trying ip-address 104.20.60.241
[ DEBUG ] feedly backend: login
[ INFO  ] feedly: userID = 641223e2-a2c7-4a65-b927-29782a529edb
[ DEBUG ] feedly: login success
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] Ping: trying ip-address 104.20.60.241
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ DEBUG ] daemon: bus aquired
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] menu
[ DEBUG ] minimize,maximize,close
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: maximize
[ DEBUG ] MainWindow: load content
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row
[ DEBUG ] ArticleList: delete HeadlineList
[ DEBUG ] ArticleList: createHeadlineList
[ DEBUG ] ArticleList: offset 0
[ DEBUG ] HeaderBar: updatebutton status true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] menu
[ DEBUG ] minimize,maximize,close
[ DEBUG ] limit: 20
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles ORDER BY date ASC LIMIT 20 OFFSET 0
[ DEBUG ] actual articles loaded: 3
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] Ping: trying ip-address 104.20.60.241
[ DEBUG ] ArticleList: createHeadlineList finished
[ DEBUG ] ArticleView: size changed
[ DEBUG ] ArticleList: restore ScrollPos
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] Ping: trying ip-address 104.20.60.241

(feedreader:30121): Gtk-WARNING **: Allocating size to GtkStack 0xb33190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[ DEBUG ] ArticleView: size changed
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row
[ DEBUG ] last clean: 2016-06-14 21:53:47
[ DEBUG ] now: 2016-06-28 22:42:57
[ DEBUG ] difference: 14.000000
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] Ping: trying ip-address 104.20.60.241
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] Ping: trying ip-address 104.20.60.241
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ INFO  ] daemon: sync started
[ DEBUG ] Ping: trying ip-address 104.20.60.241
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row
[ DEBUG ] DBusConnection: syncStarted
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0,000000
[ DEBUG ] scrollpos 0,000000
[ DEBUG ] offset 0
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: newFeedList
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row
[ DEBUG ] Grabber: process article: http://www.heise.de/newsticker/meldung/Kursmanipulation-bei-Telekom-Austria-Haftstrafen-reduziert-3225090.html?wt_mc=rss.ho.beitrag.rdf
[ DEBUG ] DBusConnection: updateFeedList
[ DEBUG ] Grabber: using config heise.de.txt
[ DEBUG ] Grabber: config found
[ DEBUG ] DBusConnection: updateArticleList
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0,000000
[ DEBUG ] scrollpos 0,000000
[ DEBUG ] offset 0
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 2)  ORDER BY date ASC LIMIT 2 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 2
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles ORDER BY date ASC LIMIT 5 OFFSET 0
[ DEBUG ] actual articles loaded: 3
[ DEBUG ] ArticleList: 0 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] Grabber: download success
[ DEBUG ] Grabber: empty article preped
[ DEBUG ] Grabber: start parsing
[ DEBUG ] Grabber: parse html
[ DEBUG ] Grabber: html parsed
[ DEBUG ] Grabber: grab next page url
[ DEBUG ] Grabber: grab single page view
[ DEBUG ] Grabber: single page url http://www.heise.de/newsticker/meldung/Kursmanipulation-bei-Telekom-Austria-Haftstrafen-reduziert-3225090.html?view=print
[ DEBUG ] Grabber: get title
[ DEBUG ] Grabber: get author
[ DEBUG ] Grabber: get date
[ DEBUG ] Grabber: strip junk
[ DEBUG ] Grabber: strip //nav
[ DEBUG ] Grabber: strip //time
[ DEBUG ] Grabber: strip //header
[ DEBUG ] Grabber: strip //h4[@class='author']
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/h3
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/figcaption
[ DEBUG ] Grabber: strip //p[@class='news_datum']
[ DEBUG ] Grabber: strip //p[@class='artikel_datum']
[ DEBUG ] Grabber: strip //p[@class='news_navi']
[ DEBUG ] Grabber: strip //p[@class='printversion']
[ DEBUG ] Grabber: strip //a[contains(@href, 'mailto')]
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/h2
[ DEBUG ] Grabber: strip //p[@class='themen_foren']
[ DEBUG ] Grabber: strip //style
[ DEBUG ] Grabber: strip //span[@class='source']
[ DEBUG ] Grabber: strip id's and class
[ DEBUG ] Grabber: complete urls
[ DEBUG ] GrabberUtils: repairURL xpath:"//img" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"href"
[ DEBUG ] GrabberUtils: repairURL xpath:"//object" attr:"data"
[ DEBUG ] Grabber: strip instapaper and readability
[ DEBUG ] Grabber: strip invisible elements
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all comments
[ DEBUG ] Grabber: strip all empty url-tags
[ DEBUG ] Grabber: get body
[ ERROR ] //div[@class='meldung_wrapper']
[ DEBUG ] Grabber: body found
[ DEBUG ] GrabberUtils: save Images: tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_1550fd4305f:2796c3c:fa2e1b2, feed/http://www.heise.de/newsticker/heise.rdf
[ DEBUG ] GrabberUtils: download Image http://1.f.ix.de/scale/geometry/695/q75/imgs/18/1/8/2/4/0/6/8/Logo_TAG-030fed1b9b10440f.jpeg
[ DEBUG ] GrabberUtils: download Image http://1.f.ix.de/imgs/18/1/8/2/4/0/6/8/IMG_3716-3b70f0312e1064c2.jpeg
[ DEBUG ] GrabberUtils: download Image http://1.f.ix.de/imgs/18/1/8/2/4/0/6/8/Alejandro_Plater-a833b35eb68cacd7.jpeg
[ DEBUG ] GrabberUtils: postProcessing
[ DEBUG ] GrabberUtils: postProcessing done
[ DEBUG ] Grabber: title: Kursmanipulation bei Telekom Austria: Haftstrafen reduziert
[ DEBUG ] Grabber: process article: http://www.heise.de/newsticker/meldung/Heute-im-Live-Stream-XPC-Online-Konferenz-zur-Cross-Platform-Entwicklung-3225092.html?wt_mc=rss.ho.beitrag.rdf
[ DEBUG ] Grabber: using config heise.de.txt
[ DEBUG ] Grabber: config found
[ DEBUG ] Grabber: download success
[ DEBUG ] Grabber: empty article preped
[ DEBUG ] Grabber: start parsing
[ DEBUG ] Grabber: parse html
[ DEBUG ] Grabber: html parsed
[ DEBUG ] Grabber: grab next page url
[ DEBUG ] Grabber: grab single page view
[ DEBUG ] Grabber: single page url http://www.heise.de/newsticker/meldung/Heute-im-Live-Stream-XPC-Online-Konferenz-zur-Cross-Platform-Entwicklung-3225092.html?view=print
[ DEBUG ] Grabber: get title
[ DEBUG ] Grabber: get author
[ DEBUG ] Grabber: get date
[ DEBUG ] Grabber: strip junk
[ DEBUG ] Grabber: strip //nav
[ DEBUG ] Grabber: strip //time
[ DEBUG ] Grabber: strip //header
[ DEBUG ] Grabber: strip //h4[@class='author']
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/h3
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/figcaption
[ DEBUG ] Grabber: strip //p[@class='news_datum']
[ DEBUG ] Grabber: strip //p[@class='artikel_datum']
[ DEBUG ] Grabber: strip //p[@class='news_navi']
[ DEBUG ] Grabber: strip //p[@class='printversion']
[ DEBUG ] Grabber: strip //a[contains(@href, 'mailto')]
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/h2
[ DEBUG ] Grabber: strip //p[@class='themen_foren']
[ DEBUG ] Grabber: strip //style
[ DEBUG ] Grabber: strip //span[@class='source']
[ DEBUG ] Grabber: strip id's and class
[ DEBUG ] Grabber: complete urls
[ DEBUG ] GrabberUtils: repairURL xpath:"//img" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"href"
[ DEBUG ] GrabberUtils: repairURL xpath:"//object" attr:"data"
[ DEBUG ] Grabber: strip instapaper and readability
[ DEBUG ] Grabber: strip invisible elements
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all comments
[ DEBUG ] Grabber: strip all empty url-tags
[ DEBUG ] Grabber: get body
[ ERROR ] //div[@class='meldung_wrapper']
[ DEBUG ] Grabber: body found
[ DEBUG ] GrabberUtils: save Images: tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_1550fd4305f:2796c3d:fa2e1b2, feed/http://www.heise.de/newsticker/heise.rdf
[ DEBUG ] GrabberUtils: download Image http://1.f.ix.de/scale/geometry/695/q75/imgs/18/1/8/2/4/0/7/0/xpc-eb12a9ba597c6159.png
[ DEBUG ] GrabberUtils: postProcessing
[ DEBUG ] GrabberUtils: postProcessing done
[ DEBUG ] Grabber: title: Heute im Live-Stream: XPC – Online-Konferenz zur Cross-Platform-Entwicklung
[ DEBUG ] Grabber: process article: http://www.golem.de/news/niedrige-preise-iphone-7-soll-bis-zu-256-gbyte-speicher-bieten-1606-121249-rss.html
[ DEBUG ] Grabber: using config golem.de.txt
[ DEBUG ] Grabber: config found
[ DEBUG ] Grabber: download redirected - 301
[ DEBUG ] Grabber: new url is: http://www.golem.de/news/niedrige-preise-iphone-7-soll-bis-zu-256-gbyte-speicher-bieten-1606-121249.html
[ DEBUG ] Grabber: download success
[ DEBUG ] Grabber: empty article preped
[ DEBUG ] Grabber: start parsing
[ DEBUG ] Grabber: parse html
[ DEBUG ] Grabber: html parsed
[ DEBUG ] Grabber: grab next page url
[ DEBUG ] Grabber: get title
[ DEBUG ] Grabber: get author
[ DEBUG ] Grabber: get date
[ DEBUG ] Grabber: strip junk
[ DEBUG ] Grabber: strip //img[@src='']
[ DEBUG ] Grabber: strip //li[not(*)]
[ DEBUG ] Grabber: strip //div[contains(@style,'margin')]
[ DEBUG ] Grabber: strip //figure[contains(@id,'gvideo')]
[ DEBUG ] Grabber: strip id's and class
[ DEBUG ] Grabber: complete urls
[ DEBUG ] GrabberUtils: repairURL xpath:"//img" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"href"
[ DEBUG ] GrabberUtils: repairURL xpath:"//object" attr:"data"
[ DEBUG ] Grabber: strip instapaper and readability
[ DEBUG ] Grabber: strip invisible elements
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all comments
[ DEBUG ] Grabber: strip all empty url-tags
[ DEBUG ] Grabber: get body
[ DEBUG ] Grabber: body found
[ DEBUG ] GrabberUtils: save Images: jF7jVEe/yvZDjBGWeWE8nizmukpqnxO3Na1FH2PsUj8=_1550fe149ad:27cadbc:9f72fccb, feed/http://www.golem.de/rss.php?feed=RSS1.0
[ DEBUG ] GrabberUtils: download Image http://www.golem.de/1606/121249-120603-i_rc.jpg
[ DEBUG ] GrabberUtils: postProcessing
[ DEBUG ] GrabberUtils: postProcessing done
[ DEBUG ] Grabber: title: Niedrige Preise: iPhone 7 soll bis zu 256 GByte Speicher bieten
[ DEBUG ] Grabber: author: Andreas Donath
[ DEBUG ] Grabber: date: 2.6.2016, 08:30
[ DEBUG ] Grabber: process article: http://www.golem.de/news/vitrima-gopro-soll-bald-in-3d-filmen-1606-121250-rss.html
[ DEBUG ] Grabber: using config golem.de.txt
[ DEBUG ] Grabber: config found
[ DEBUG ] Grabber: download redirected - 301
[ DEBUG ] Grabber: new url is: http://www.golem.de/news/vitrima-gopro-soll-bald-in-3d-filmen-1606-121250.html
[ DEBUG ] Grabber: download success
[ DEBUG ] Grabber: empty article preped
[ DEBUG ] Grabber: start parsing
[ DEBUG ] Grabber: parse html
[ DEBUG ] Grabber: html parsed
[ DEBUG ] Grabber: grab next page url
[ DEBUG ] Grabber: get title
[ DEBUG ] Grabber: get author
[ DEBUG ] Grabber: get date
[ DEBUG ] Grabber: strip junk
[ DEBUG ] Grabber: strip //img[@src='']
[ DEBUG ] Grabber: strip //li[not(*)]
[ DEBUG ] Grabber: strip //div[contains(@style,'margin')]
[ DEBUG ] Grabber: strip //figure[contains(@id,'gvideo')]
[ DEBUG ] Grabber: strip id's and class
[ DEBUG ] Grabber: complete urls
[ DEBUG ] GrabberUtils: repairURL xpath:"//img" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"href"
[ DEBUG ] GrabberUtils: repairURL xpath:"//object" attr:"data"
[ DEBUG ] Grabber: strip instapaper and readability
[ DEBUG ] Grabber: strip invisible elements
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all comments
[ DEBUG ] Grabber: strip all empty url-tags
[ DEBUG ] Grabber: get body
[ DEBUG ] Grabber: body found
[ DEBUG ] GrabberUtils: save Images: jF7jVEe/yvZDjBGWeWE8nizmukpqnxO3Na1FH2PsUj8=_1550fe149ad:27cadbd:9f72fccb, feed/http://www.golem.de/rss.php?feed=RSS1.0
[ DEBUG ] GrabberUtils: download Image http://www.golem.de/1606/121250-120606-i_rc.jpg
[ DEBUG ] GrabberUtils: download Image http://scr3.golem.de/screenshots/1606/Vitrima/thumb620/1823608966.jpg
[ DEBUG ] GrabberUtils: postProcessing
[ DEBUG ] GrabberUtils: broken = <iframe id="ytplayer" type="text/html" width="620px" height="374px" src="http://www.youtube.com/embed/O40A1m_H2yY?autoplay=0" frameborder="0" allowfullscreen=""/>
[ DEBUG ] GrabberUtils: fixed = <iframe id="ytplayer" type="text/html" width="620px" height="374px" src="http://www.youtube.com/embed/O40A1m_H2yY?autoplay=0" frameborder="0" allowfullscreen=""></iframe>
[ DEBUG ] GrabberUtils: postProcessing done
[ DEBUG ] Grabber: title: Vitrima: Gopro soll bald in 3D filmen
[ DEBUG ] Grabber: author: Andreas Donath
[ DEBUG ] Grabber: date: 2.6.2016, 08:36
[ DEBUG ] Grabber: process article: http://www.heise.de/newsticker/meldung/Uber-bekommt-3-5-Milliarden-Dollar-aus-Saudi-Arabien-3225123.html?wt_mc=rss.ho.beitrag.rdf
[ DEBUG ] Grabber: using config heise.de.txt
[ DEBUG ] Grabber: config found
[ DEBUG ] Grabber: download success
[ DEBUG ] Grabber: empty article preped
[ DEBUG ] Grabber: start parsing
[ DEBUG ] Grabber: parse html
[ DEBUG ] Grabber: html parsed
[ DEBUG ] Grabber: grab next page url
[ DEBUG ] Grabber: grab single page view
[ DEBUG ] Grabber: single page url http://www.heise.de/newsticker/meldung/Uber-bekommt-3-5-Milliarden-Dollar-aus-Saudi-Arabien-3225123.html?view=print
[ DEBUG ] Grabber: get title
[ DEBUG ] Grabber: get author
[ DEBUG ] Grabber: get date
[ DEBUG ] Grabber: strip junk
[ DEBUG ] Grabber: strip //nav
[ DEBUG ] Grabber: strip //time
[ DEBUG ] Grabber: strip //header
[ DEBUG ] Grabber: strip //h4[@class='author']
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/h3
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/figcaption
[ DEBUG ] Grabber: strip //p[@class='news_datum']
[ DEBUG ] Grabber: strip //p[@class='artikel_datum']
[ DEBUG ] Grabber: strip //p[@class='news_navi']
[ DEBUG ] Grabber: strip //p[@class='printversion']
[ DEBUG ] Grabber: strip //a[contains(@href, 'mailto')]
[ DEBUG ] Grabber: strip //div[@class='gallery compact']/h2
[ DEBUG ] Grabber: strip //p[@class='themen_foren']
[ DEBUG ] Grabber: strip //style
[ DEBUG ] Grabber: strip //span[@class='source']
[ DEBUG ] Grabber: strip id's and class
[ DEBUG ] Grabber: complete urls
[ DEBUG ] GrabberUtils: repairURL xpath:"//img" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"src"
[ DEBUG ] GrabberUtils: repairURL xpath:"//a" attr:"href"
[ DEBUG ] GrabberUtils: repairURL xpath:"//object" attr:"data"
[ DEBUG ] Grabber: strip instapaper and readability
[ DEBUG ] Grabber: strip invisible elements
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all scripts
[ DEBUG ] Grabber: strip all comments
[ DEBUG ] Grabber: strip all empty url-tags
[ DEBUG ] Grabber: get body
[ ERROR ] //div[@class='meldung_wrapper']
[ DEBUG ] Grabber: body found
[ DEBUG ] GrabberUtils: save Images: tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_1550fefab64:27f6984:9f72fccb, feed/http://www.heise.de/newsticker/heise.rdf
[ DEBUG ] GrabberUtils: download Image http://1.f.ix.de/scale/geometry/695/q75/imgs/18/1/8/2/4/0/9/2/urn-newsml-dpa-com-20090101-160408-99-505378_large_4_3-9591cfdca8755677.jpeg
[ DEBUG ] GrabberUtils: postProcessing
[ DEBUG ] GrabberUtils: postProcessing done
[ DEBUG ] Grabber: title: Uber bekommt 3,5 Milliarden Dollar aus Saudi-Arabien
[ DEBUG ] Grabber: process article: http://www.heise.de/newsticker/meldung/Neue-Produkte-Apple-laedt-zur-Keynote-am-13-Juni-3225057.html?wt_mc=rss.ho.beitrag.rdf
[ DEBUG ] Grabber: using config heise.de.txt
[ DEBUG ] Grabber: config found
[ DEBUG ] Grabber: download success
[ DEBUG ] Grabber: empty article preped

**Comment by jangernert** [comment] 2016-06-30 14:09
No idea why your database gets wiped randomly =/
But I created a scenario in feedreader-debugger that causes articles to appear multiple times in the articleList. It happens when the updateArticleList-signal gets somehow triggered multiple times and the second update starts even though the fist update wasn't finished.
I will look for the reason this happens in the first place. And also prevent the articleList form staring a second update when the first one is not finished.

**Comment by fb87** [comment] 2016-06-30 19:46
You could implement the daemon as a state machine – this way it's easy to ignore multiple trigger signals when they mustn't occur. ;)

**Comment by jangernert** [comment] 2016-07-03 14:07
Not sure if that would be the way to go, since I have to react to lots of stuff which would result in a ton of different states (different combination of things). So I guess I would have needed to think about this before writing all this code^^
With the newest commit in master I now lock the articleList during updates (and creating new ones) and queue up all additional update requests. This solves the testcase that triggered the issue with the feedreader-debugger. Any improvements on your side?

**Comment by fb87** [comment] 2016-07-05 22:24
Sadly no, just now all feeds were trashed again. But I haven't updated from source since because of lacking time and this haven't played around with fr-dbg. Will update later, when the sync is complete. Can you find some piece in the code, that could lead to losing or deleting the database?

**Comment by jangernert** [comment] 2016-07-05 23:45
Is it just the articles that disappear, or everything including feeds and categories?
There is one function called "restetDB". But it is only called when you click the red button on the reset-page - the one you get when you click "Change Account" in the gmenu.

Then there is a function that regularly deletes old articles after each sync based on what you set in the settings "internals->delte articles after". It selects articles that older than X days, were not in the batch of sync-count last synced articles and are NOT starred, then passes the id's to another function and deletes them one by one. Every time I explicitly test this, everything works fine. But a few times I lost some old starred articles in the db. So it could be misbehaving sometimes maybe?!?
There should be a info log-message in the daemon-log every time this triggers with the exact query. Something like this:

> SELECT articleID, feedID FROM main.articles WHERE date <= datetime('now', '-168 days') AND marked = 10 AND rowid BETWEEN 1 AND 1125

I think I will set up a watchdog for the db that barks every time something is removed from the db and see when it triggers. Maybe there is some WAL or other sqlite shenanigans going on that I'm not aware of.

**Comment by fb87** [comment] 2016-07-05 23:50
All the feeds disappear for some seconds, then they reappear again, but it takes at least 10 minutes for syncing, so I assume everything to get fetched again. I'm really not sure, but I think it happened immediately just after hitting the sync button.

I try to always run it within a terminal and copy you the log when it happens again.

**Comment by jangernert** [comment] 2016-07-05 23:56
Can you check the db with some kind of viewer next time? I personally use the firefox sqlite addon. There is also a sqlite browser in the software center in fedora.

**Comment by fb87** [comment] 2016-07-06 00:03
Ok

**Comment by jangernert** [comment] 2016-07-06 00:41
With the latest commit the daemon.log in $HOME/.local/share/feedreader/ should also work correctly now. Until now I was always getting overwritten when the UI was started. So now you can check the daemon.log AFTER something wonky happens with your DB. Just don't start a new instance of the feedreader-daemon again, as this will overwrite the log again.

**Comment by fb87** [comment] 2016-07-13 20:29
So now I see in the feed pane that new articles are fetched, but when selecting a feed or „all“ noting gets displayed. Both overview and article pane display „No unread articles in the feed "heise online News" could be found“ (even when heise isn't selected) and „Kein Artikel ausgewählt“... well, there's also some translation missing ;)
Regarding the bug title: Feeds getting displayed multiple times don't occurr anymore.

Daemon log:
http://pastebin.com/nt8qfmnL

**Comment by jangernert** [comment] 2016-07-21 23:27
Since this is fixed, I'll close the bug report to keep a better overview.

**Closed by jangernert** 2016-07-21 23:27 UTC
Labels: bug
