### ISSUE TITLE
Crashing while scrolling through the articles

### ISSUE THREAD

**Issue by Strubbl** [jangernert/FeedReader#835] opened 2019-01-18 19:33 UTC
OS: Archlinux
WM: i3wm

$ feedreader --version
Version: 2.6.0
Git Commit: 939ea589838492dfa2971047cb1b51a2099ff749

This is the error i get while going through the article list with the down key:
```
Error while executing 'addr2line -f -e /usr/bin/feedreader 0x7fbf40565672': Too many open files
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGABRT)
   The reason is likely a failed assertion (assert...).
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?
```

**Comment by Strubbl** [comment] 2019-01-18 20:05
i guess this bug is similar to #834

**Comment by brendanlong** [comment] 2019-01-24 15:39
I'm going to close this as a duplicate of #834 since I think it's the same bug and it's easier to keep track of one issue.

**Closed by brendanlong** 2019-01-24 15:39 UTC
