### ISSUE TITLE
Feature: Selectable text in the article view

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#145] opened 2016-06-18 20:43 UTC
Don't know if it's possible with the renderer you use, but would be nice if text could be selected for copying. :)

**Comment by jangernert** [comment] 2016-06-18 21:24
duplicate of #123
it is available as a tweak for advanced users. I want to keep the defaults simple and clean. That's why this is only available via gsettings/dconf
just open dconf-editor and navigate to org->gnome->feedreader->tweaks and check article-select-text

**Closed by jangernert** 2016-06-18 21:24 UTC

**Comment by fb87** [comment] 2016-06-18 21:29
Thx
