### ISSUE TITLE
Crash on Copy URL

### ISSUE THREAD

**Issue by asm0dey** [jangernert/FeedReader#749] opened 2018-08-29 19:27 UTC
Hi again, guys.

Today I've found new issue. Application crashes when I try to Copy URL of feed like this: ![](https://media.giphy.com/media/fWgeJUN2ORqQBLl2ZH/giphy.gif)

With following data in log:

```
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

    #1  <unknown>   in 'feed_reader_feed_list_copySelectedFeedURL'
        at /lib/libFeedReader.so
    #2  <unknown>   in 'g_closure_invoke'
        at /lib/libgobject-2.0.so.0
    #3  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #4  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #5  <unknown>   in 'g_closure_invoke'
        at /lib/libgobject-2.0.so.0
    #6  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #7  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #8  <unknown>   in 'g_closure_invoke'
        at /lib/libgobject-2.0.so.0
    #9  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #10  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #11  <unknown>   in 'g_closure_invoke'
        at /lib/libgobject-2.0.so.0
    #12  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #13  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #14  <unknown>   in 'ffi_call_unix64'
        at /lib/libffi.so.6
    #15  <unknown>   in 'ffi_call'
        at /lib/libffi.so.6
    #16  <unknown>   in 'g_cclosure_marshal_generic_va'
        at /lib/libgobject-2.0.so.0
    #17  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #18  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #19  <unknown>   in 'g_cclosure_marshal_VOID__BOXEDv'
        at /lib/libgobject-2.0.so.0
    #20  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #21  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #22  <unknown>   in 'gtk_event_controller_handle_event'
        at /lib/libgtk-3.so.0
    #23  <unknown>   in 'g_signal_emit_valist'
        at /lib/libgobject-2.0.so.0
    #24  <unknown>   in 'g_signal_emit'
        at /lib/libgobject-2.0.so.0
    #25  <unknown>   in 'gtk_main_do_event'
        at /lib/libgtk-3.so.0
    #26  <unknown>   in 'g_main_context_dispatch'
        at /lib/libglib-2.0.so.0
    #27  <unknown>   in 'g_main_context_iteration'
        at /lib/libglib-2.0.so.0
    #28  <unknown>   in 'g_application_run'
        at /lib/libgio-2.0.so.0
    #29  <unknown>   in 'feed_reader_main'
        at /lib/libFeedReader.so
    #30  <unknown>   in '__libc_start_main'
        at 
```

**Comment by brendanlong** [comment] 2018-08-29 19:36
This works for me, but I added a few more null checks in 6d62a9bfa29714dcb318dc9c66b00bf8b19e4b58 that might help though.

**Comment by asm0dey** [comment] 2018-08-29 19:46
Doen't crash anymore, but still doesn't copy url :(

**Comment by brendanlong** [comment] 2018-08-29 19:50
I'm betting this is either a bug in TT-RSS or in the TT-RSS plugin, and the Feed URL is NULL.

I don't have a TT-RSS account so I can't fix this myself, but I can review a pull request if you figure out what's wrong.

**Comment by brendanlong** [comment] 2018-08-29 20:40
Unfortunately I don't really have time to look into this :(

**Comment by bilelmoussaoui** [comment] 2018-10-08 23:31
Duplicate of https://github.com/jangernert/FeedReader/issues/538

**Closed by bilelmoussaoui** 2018-10-08 23:31 UTC
Labels: bug
