### ISSUE TITLE
Update Ubuntu ppa to 2.0

### ISSUE THREAD

**Issue by epocopa** [jangernert/FeedReader#374] opened 2017-02-15 14:07 UTC
Could you please update the Ubuntu ppa to FeedReader 2.0?
Thanks!

**Comment by bil-elmoussaoui** [comment] 2017-02-15 14:13
By @jangernert 

> Launchpad.net messes up the path of a dynamically created vapi-file and fails the build.
If someone can resolve the problem with launchpad.net he/she is welcome to create a new build.
https://launchpadlibrarian.net/289455962/buildlog_ubuntu-yakkety-amd64.feedreader_2.0.0~r1347+pkg25~ubuntu16.10.1_BUILDING.txt.gz
Furthermore I wanted to discontinue the ppa for a long time now to let someone with more knowledge and time for it take over. Packaging is not something I'm interested in. All the packages for other distributions are already maintained by other people.
Also duplicate of #244 #340 #305 #245 #243

**Closed by bil-elmoussaoui** 2017-02-15 14:13 UTC

**Comment by epocopa** [comment] 2017-02-15 14:33
I wasn't talking about Ubuntu 16.10, I'm using ElementaryOS, based on Ubuntu 16.04

**Comment by jscurtu** [comment] 2017-02-15 14:40
@epocopa Gtk is too old.. sorry

**Comment by jangernert** [comment] 2017-02-15 15:14
But there is a ppa for flatpak on Ubuntu. So you could run the flatpak with the correct run-time.

**Comment by khurshid-alam** [comment] 2017-02-21 14:35
First, It needs to patched for vala-0.34

`sed -i "s/static const/const/g" *.vala`

**Comment by khurshid-alam** [comment] 2017-03-12 07:34
Open a new bug "Packaging For Ubuntu/Debian" and attached `help-needed` tag.
