### ISSUE TITLE
Core dump on wallabag share configuration

### ISSUE THREAD

**Issue by ssaavedra** [jangernert/FeedReader#438] opened 2017-03-29 11:38 UTC
When I enter valid data for my wallabag instance, and click login (or press enter after filling in all fields) the app crashes.

This is the data that gets output (I redacted the access and refresh tokens from the output)

```
...
[ DEBUG ] Share: refreshAccounts
Memory pressure relief: Empty the PageCache: =dirty (at 9449472 bytes)
Memory pressure relief: Prune MemoryCache live resources: =dirty (at 9449472 bytes)
Memory pressure relief: Drain CSSValuePool: =dirty (at 9449472 bytes)
Memory pressure relief: Discard StyleResolvers: =dirty (at 9449472 bytes)
Memory pressure relief: Discard all JIT-compiled code: =dirty (at 9449472 bytes)
Memory pressure relief: Dropping buffered data from paused media elements: =dirty (at 9449472 bytes)
Memory pressure relief: Purge inactive FontData: =dirty (at 9449472 bytes)
Memory pressure relief: Clear WidthCaches: =dirty (at 9449472 bytes)
Memory pressure relief: Discard Selector Query Cache: =dirty (at 9449472 bytes)
Memory pressure relief: Prune MemoryCache dead resources: =dirty (at 9449472 bytes)
Memory pressure relief: Prune presentation attribute cache: =dirty (at 9449472 bytes)
Memory pressure relief: Run malloc_trim: +dirty 86016 bytes (from 9449472 to 9535488)
Memory pressure relief: Release free FastMalloc memory: -dirty 8192 bytes (from 9535488 to 9527296)
[ DEBUG ] WallabagAPI getAccessToken
[ DEBUG ] {"access_token":"REDACTED_ACCESS_TOKEN","expires_in":3600,"token_type":"bearer","scope":null,"refresh_token":"REDACTED_REFRESH_TOKEN"}

(feedreader:3839): GLib-GIO-ERROR **: Settings schema 'org.gnome.feedreader.share.wallabag' does not contain a key named 'wallabag'
zsh: trace trap (core dumped)  feedreader
[ssaavedra@sparkle] ~ $
```

**Comment by jangernert** [comment] 2017-03-29 13:20
What version do you have installed on your system? Also: complete logs?

**Comment by ssaavedra** [comment] 2017-03-29 21:28
Sure, version 2.0.2 installed from the Fedora repos.

Where can I get more complete logs?

**Comment by jangernert** [comment] 2017-03-29 22:21
On investigation this seems like a duplicate of #405.
Please try master and see if it is fixed for you as well :)
Have to release 2.0.3 at some point when a few more fixes are ready.

**Comment by ssaavedra** [comment] 2017-03-30 11:04
Right. I've tried the latest FlatPak version (as per #405) and it does work
there, so it seems that 2.0.2 was released without the schema change, as
mentioned there.

Thanks!

**Closed** 2017-03-30 20:00 UTC
