### ISSUE TITLE
Feedreader (git version) doesn't display articles

### ISSUE THREAD

**Issue by fturco** [jangernert/FeedReader#152] opened 2016-07-16 13:36 UTC
I'm testing feedreader-git from the AUR (1.6.beta.1.r103.g6b5eb93-1).

Feedreader tells me that I have some unread articles, but it refuses to display them to me (no unread articles for search term "" could be found):

![screenshot from 2016-07-16 15-28-31](https://cloud.githubusercontent.com/assets/5459866/16895090/844c0cda-4b6a-11e6-9fba-2dfd6148c1a6.png)

**Comment by bil-elmoussaoui** [comment] 2016-07-16 13:39
Have you tried killing feedreader-daemon and feedreader after your update to feedreader-git? if not try this `pkill feedreader-daemon && pkill feedreader` reopen feedreader and see if everything works fine?

**Comment by fturco** [comment] 2016-07-16 13:45
I tried your command and it works now! I was not aware of the existence of a daemon. Thank you!

**Comment by bil-elmoussaoui** [comment] 2016-07-16 13:46
You're welcome!

**Comment by fturco** [comment] 2016-07-17 17:59
I still have this problem. I had to run the `pkill` commands a few times today for temporarily solving the problem. Not sure how to reliably reproduce this.

**Comment by jangernert** [comment] 2016-07-17 19:19
do you have 2 different versions of feedreader installed on your system now?

**Comment by fturco** [comment] 2016-07-17 19:25
No. I just have `feedreader-git` from AUR which replaced `feedreader`. It is not possible to install both at the same time due to the `conflicts` variable in `PKGBUILD`.

**Comment by jangernert** [comment] 2016-07-17 19:47
The (wrong) message seems to be a bug and should be fixed now in master. As to why that message appears in the first place: Can you post the log of the feedreader UI ?

**Comment by fturco** [comment] 2016-07-17 20:36
Sure:

[ui.log.txt](https://github.com/jangernert/FeedReader/files/368113/ui.log.txt)

I had to rename `ui.log` to `ui.log.txt` for GitHub to accept it.

**Comment by fturco** [comment] 2016-07-17 20:43
Updated from 1.6.beta.1.r103.g6b5eb93-1 to 1.6.beta.1.r104.g7e1ce87-1. I'm going to test it tomorrow.

**Comment by jangernert** [comment] 2016-07-17 23:15
So first of all, according to the log FeedReader does not start like this, but you somehow produce this state. That is INFORMATION I NEEED in the first place. How can I know what went wrong when I don't even know what happened?
So if you report a bug like this next time please give a detailed description of what you did to trigger the bug.
Reading the log for over 30 min I GUESS you read articles in the "unread"-mode until the list was empty and a message like "no unread articles could be found" popped up, then a update after a automatic sync happened. The update locked the articleList, then redirected to create a new list instead because the old one was empty without clearing the lock. So no further update or new list could happen.
IF that was the case I think I just fixed the issue.

**Comment by fturco** [comment] 2016-07-18 11:35
Yes, I read articles in unread-mode until the list was empty. Then I went away for a few hours while it periodically updated feeds. But when I went back to Feed Reader it didn't allow me to read any new articles. The only thing I could see was the count numbers for the new articles. I'm sorry for not being more precise before.

**Comment by jangernert** [comment] 2016-07-18 11:41
Can you confirm that the issue is fixed with the newest revision?

**Comment by fturco** [comment] 2016-07-18 11:53
Not yet. I just upgraded from r104 to r105. I'm going to test the new version today while using it as described before.

**Comment by jangernert** [comment] 2016-07-21 23:29
Any news over here?

**Comment by fturco** [comment] 2016-07-22 08:19
I tested r105 for several days but I couldn't reproduce any of the two aforementioned problems.

**Comment by jangernert** [comment] 2016-07-22 10:53
Okay, then I will close this for now.

**Closed by jangernert** 2016-07-22 10:53 UTC
Labels: bug
