### ISSUE TITLE
Articles aren't shown anymore

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#192] opened 2016-08-31 18:51 UTC
Now after reading some articles, I got four remaining ones, but now somehow neither of them can be displayed.

![feedreader_011](https://cloud.githubusercontent.com/assets/10520767/18142123/788b2252-6fbc-11e6-8150-a35a6013a6b0.png)
[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/448045/feedreader.tar.gz)

**Comment by jangernert** [comment] 2016-08-31 20:41
Same behavior after closing and restarting the UI?

**Comment by JoshMedeiros** [comment] 2016-09-01 12:04
I'm experiencing the same issue under Arch Linux. It appears to happen with the current version of webkit2gtk (2.12.4-1).

Downgrading the package back to webkit2gtk (2.12.3-1) appears to fix the issue, so it could be a bug in the new version.

**Comment by jangernert** [comment] 2016-09-01 13:32
@JoshMedeiros: If you are experiencing #190 the bug was fixed in version 1.6.2 ;)

**Comment by fb87** [comment] 2016-09-01 20:54
Closing and starting leads to normal behaviour.

**Comment by jangernert** [comment] 2016-09-01 21:15
If I can't reproduce the issue I can't fix it =/

**Comment by fb87** [comment] 2016-09-01 21:15
Do my logs help you anyhow?

**Comment by jangernert** [comment] 2016-09-01 21:36
Kind of. I see what is going wrong. A new article is requested to be loaded while the article-view is still busy. The article-view successfully cancel the ongoing load and starts loading the new article. But somehow the view still reports to be busy. No idea why though.
At least, that's what I THINK is happening :D

**Comment by jangernert** [comment] 2016-09-01 21:39
If you have some basic Java or C# knowledge I can help you find the right bits of code so you can try to debug your issues yourself if you can reproduce them on your pc ;)
(pretty much all the open bug-reports are from you :D)

**Comment by fb87** [comment] 2016-09-01 21:41
By the way, since a few days no text is rendered by WebKitGTK+, I just see the image of the article. I didn't report this because I thought it will be obvious and fatal enough to be fixed by WebKitGTK+ in a few days, but maybe this is related.

I do C, C++ and newly (trying) Rust but got absolutely no time at the moment. Maybe I find some time in a few weeks.

**Comment by jangernert** [comment] 2016-09-01 21:57
Actually it was some faulty CSS in FeedReader that somehow worked with previous versions of webkitgtk+.
It is fixed in version 1.6.2 (#190) which should hit fedora soon. It is currently in testing:
https://bodhi.fedoraproject.org/updates/?packages=feedreader

**Comment by fb87** [comment] 2016-09-01 22:08
I git fetched and after an install I still was just displayed version 1.6 beta, not 1.6.2. Nothing changed.

**Comment by jangernert** [comment] 2016-09-01 22:12
could it be that you have the package-version in /usr/bin and the git-version in /usr/local/bin (that's what cmake defaults to)?

**Comment by fb87** [comment] 2016-09-01 22:19
No, even un- and reinstalled it.

$ feedreader --version
Version: 1.6 beta
Git Commit: 073ceda24408968cedbe8a0ee57e863e91508375

$ dnf info feedreader
Letzte Prüfung auf abgelaufene Metadaten: vor 1 day, 1:40:05 am Wed Aug 31 22:38:00 2016.
Verfügbare Pakete
Name        : feedreader
Arch        : x86_64
Epoch       : 0
Version     : 1.6
Release     : 0.1.beta1.fc24
Größe       : 1.3 M
Paketquelle : fedora
Zusammenfas : RSS desktop client
URL         : https://github.com/jangernert/FeedReader
Lizenz      : GPLv3+
Beschreibun : FeedReader is a modern desktop application designed to complement
            : existing web-based RSS accounts. It combines all the advantages of
            : web based services like synchronization across all your devices
            : with everything you expect from a modern desktop application.

**Comment by jangernert** [comment] 2016-09-01 22:22
Did you do `cmake ..` or `cmake -DINSTALL_PREFIX=/usr ..`?
If you did the first what is the output of `/usr/local/bin/feedreader --version` ?

**Comment by jangernert** [comment] 2016-09-01 22:25
If you can't get the newest version to run just go to your install prefix (/usr I guess) and then ./share/FeedReader/ArticleView/style.css and delete all the font-stuff that uses the files in the assets-folders
That's basically all that changed: e36de3ae08320d9b6ac58b39cadb508d8a5525f4

**Comment by fb87** [comment] 2016-09-01 22:34
Deleted the Git directory and cloned it new, now I get these errors – though it compiled previously without errors? O_o

-- Checking for modules 'gtk+-3.0;json-glib-1.0;gee-0.8;libsoup-2.4;sqlite3;libsecret-1;libnotify;libxml-2.0;rest-0.7;webkit2gtk-4.0;gstreamer-1.0;gstreamer-pbutils-1.0;goa-1.0;libpeas-1.0'
--   No package 'gstreamer-1.0' found
--   No package 'gstreamer-pbutils-1.0' found
--   No package 'goa-1.0' found
--   No package 'libpeas-1.0' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found

**Comment by jangernert** [comment] 2016-09-01 22:36
Now you are trying to compile master-branch not stable.
To change to stable type `git checkout master`.

If you WANT to compile master you need to install the development versions of these packages. I don't know the exact package names from the top of my head. But `dnf search` should help you. They all end in "-devel".

**Comment by fb87** [comment] 2016-09-01 22:51
I think you mean "git co stable" ;)

Thanks and sorry, git is still a bit confusing to me...

I now switched to stable and could compile it. But now ALL GTK images of FR are gone. No program icon, no in-program icons, just external icons like the feed icons. :(

Installing the Fedora version also brings up 1.6 beta, not 1.6.1…

**Comment by jangernert** [comment] 2016-09-01 23:05
Yes I meant "stable" not "master".
The "1.6 beta" is just a string I forgot to change for the release :(
Sounds like your icon-cache didn't get updated after installing. But good to hear that it now works.

**Comment by jangernert** [comment] 2016-09-02 01:25
Just thought of something:
Since you have set up a build of feedreader on your local machine already.
Can you open up ./src/Widgets/ArticleView.vala and comment out line [781](https://github.com/jangernert/FeedReader/blob/stable/src/Widgets/ArticleView.vala#L781) and [789](https://github.com/jangernert/FeedReader/blob/stable/src/Widgets/ArticleView.vala#L789) (ideally do a commit or change the [version string](https://github.com/jangernert/FeedReader/blob/stable/src/Constants.vala#L199) to verify you are running the updated version and see if this fixes your issue.
Sadly without the two lines you will sometimes see the old article for a moment before the new one is finished loading. But if it is causing bugs I guess the lines have to be removed.

**Comment by fb87** [comment] 2016-09-02 18:17
Changed it, but I cannot reproduce the bug, so I have to see if it appears again.

Do you know how to get the programm running with $LANG considered?

**Comment by jangernert** [comment] 2016-09-02 18:22
1. no, who cares about languages other than english on their pc anyway? :D
2. recompile the icon cache with [gtk-update-icon-cache](https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html)

**Comment by jangernert** [comment] 2016-09-07 11:02
Did you experience the bug ever again after the changes?

**Comment by fb87** [comment] 2016-09-07 18:33
Yes, 2 or 3 times since.

**Comment by jangernert** [comment] 2016-09-10 17:15
Is it always some specific article? Do some specific articles always trigger this behavior?
I noticed one of my articles triggers the same behavior. The html-code has some custom fonts and CSS that does not work with the latest release of webkitgtk anymore:
```
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,700italic,400,700" rel="stylesheet" type="text/css"/>
<link href="/staff/Meru/2015/wcs/s1/stylesalt.css" rel="stylesheet" type="text/css"/>
```

**Comment by fb87** [comment] 2016-09-10 17:19
I don't remember. Can you reset the state of WebkitGTK+ for every article or create and destroy it every time? Or setting it back when something is modified?

**Comment by jangernert** [comment] 2016-09-10 17:42
Well, at least my issues is now fixed on master :P 
Fixing bugs is easy if you can reproduce them on your own machine :)

**Comment by gitkrax** [comment] 2016-09-23 05:13
I just encountered this bug on my version 1.6.2. Was 1.6.2 supposed to fix this bug? Restarting seemed to help.

**Comment by jangernert** [comment] 2016-09-23 05:19
Different issue.

**Comment by gitkrax** [comment] 2016-09-23 08:04
I'm sorry, I didn't understand. Did you mean that I should start a new issue, even though the behavior I encountered was the one described in this bug?

Or did you mean that 1.6.2. was supposed to fix a different issue and therefore this issue remains? It's still open and I encountered it, so I'm guessing this one.

**Comment by jangernert** [comment] 2016-09-23 13:25
If you ever experienced the bug that was fixed in 1.6.2 you can clearly see that they are two separate issues. One was just a rendering issues due to a missing font, while here the webview does not even start loading.

**Comment by gitkrax** [comment] 2016-09-24 19:02
I've only used 1.6.2, so I haven't. Tell me if I can help figuring out a fix. I'm not really fluent in Vala or C, though.

**Comment by jangernert** [comment] 2016-09-24 21:51
The best way to help me is: Find a way to always trigger the issue reliably. Not like, sometimes it works sometimes id doesn't, no idea why. But: Do step A, then B and C and you will trigger the issue. Or maybe it depends on certain data of some articles together with unfortunate timing?
Then I can start investigating what is going wrong :)

**Comment by fb87** [comment] 2016-09-27 15:11
And how exactly should I know how to reproduce random issues? Especially when the program runs in background und at some time I switch to it and see it having crashed and crashed again? Most issues appear while syncing or at switching articles - syncing again doesn't reproduce anything and making an article unread and reading it again doesn't either.

That's why I send you your logs with debug information. Almost every instruction returns an error value, so that you can check if something's wrong. I have the strong feeling that you don't check valid return values of every instruction and function, otherwise it wouldn't be so buggy. The only thing I do is syncing and clicking through articles, and in seldom cases use starring.

**Comment by jangernert** [comment] 2016-09-27 17:02
Sice you seem to know exactly how to handle this problem: patches welcome :)

**Comment by fb87** [comment] 2016-10-05 17:12
I wanted to take a look at the code some time ago, but I stopped the moment I saw it's Vala. Got no time for learning a single-purpose language which provides not much use for me.

**Comment by jangernert** [comment] 2016-10-05 17:19
If you know java or C# you already know 97% of vala:
https://wiki.gnome.org/Projects/Vala/ValaForCSharpProgrammers
https://wiki.gnome.org/Projects/Vala/ValaForJavaProgrammers

**Comment by fb87** [comment] 2016-10-05 17:22
I'll take a look when I got some spare time. :)

**Comment by fb87** [comment] 2016-10-07 23:11
Happened again.
[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/517250/feedreader.tar.gz)

**Comment by jangernert** [comment] 2016-10-07 23:44
Can you provide the content of article `tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_157988ba623:cd4ff6:d93b8304` ?
That's the article that never even started loading and is blocking all articles from being loaded afterwards. Maybe something is wrong with the html-code?!

**Comment by fb87** [comment] 2016-10-07 23:58
If you could tell me how I translate this cryptographic numbers in an actual article, I will tell you. :)

**Comment by jangernert** [comment] 2016-10-08 00:15
This cryptic sequence of signs is the article-ID assigned by feedly. Open up the file `$HOME/.local/share/feedreader/data/feedreader-03.db` with any kind of sqlite-viewer. I personally use sqlite manager for Firefox. All articles are listed in the table "articles". Depending on your viewer-application you can search the table via the GUI. Or execute the following sql statement
```
SELECT * FROM articles WHERE articleID = "tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_157988ba623:cd4ff6:d93b8304"
```

**Comment by fb87** [comment] 2016-10-08 00:19
Thanks, here it is:
https://www.heise.de/newsticker/meldung/Googles-Kuenstliche-Intelligenz-Mobile-first-war-gestern-3341711.html?wt_mc=rss.ho.beitrag.rdf

**Comment by jangernert** [comment] 2016-10-08 00:21
Sorry if I didn't express myself clearly, but I was talking about the html-column.

**Comment by fb87** [comment] 2016-10-08 00:22
"<!DOCTYPE html SYSTEM ""1.0"">
<article:body><article>
        
        <div class=""meldung_wrapper druckversion"">
            
    
        
    

    
    <figure class=""aufmacherbild"">
            <img src=""/home/frank/.local/share/feedreader/data/images/feed_http:__www.heise.de_newsticker_heise.rdf/tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_157988ba623:cd4ff6:d93b8304/1""/>
            <figcaption>
                <p class=""caption"">CEO Sundar Pichai führt Google in ein neues Zeitalter.</p>
            </figcaption>
    </figure>
    

            
            <p class=""meldung_anrisstext""><strong>Smartphones, Chromecast, Google Home: Die ganze Hardware, die Google vorgestellt hat, ist nur Mittel zum Zweck. Für den Konzern beginnt eine neue Ära: die der Künstlichen Intelligenz.</strong></p>
            <p>In Barcelona gibt Eric Schmidt Googles neue Marschrichtung vor: ""<b>Mobile first [1]</b>"" heißt es nun für den Suchmaschinenkonzern, der mit dem Netz groß geworden ist. Das war im Februar <b>2010 auf dem Mobile World Congress [2]</b>. Der <b>Smartphone-Markt [3]</b> war im Umbruch, HSPA+ der letzte Schrei. Am Abend zuvor hatte Steve Ballmer Microsofts neues Windows Phone vorgestellt und Googles eigenes Mobilbetriebssystem Android sollte wenig später erstmals die 10-Prozent-Hürde bei den Marktanteilen nehmen.</p>
<p>

    

</p>
<h3 class=""subheading"">Googles neuer Weg</h3>
<p>Gut sechs Jahre später ist wieder Zeit für so einen Kurswechsel. Googles CEO heißt heute Sundar Pichai, damals war er im Konzern für Chrome und später auch Android verantwortlich. Als Pichai am Dienstag Googles Launch-Event eröffnet, redet er nicht über neue Smartphones oder Android-Versionen. Pichai spricht vor allem über eins: Den Assistenten. Während die Wettbewerber ihre digitalen Assistenzsysteme mit Namen wie Alexa, Cortana oder Siri vermenscheln, ist es bei Google schlicht der Assistent. </p>
<p>Das Zeitalter des Smartphones geht zu Ende, ist Pichai überzeugt. Es wird künftig nur eins von verschiedenen Mitteln sein, mit <b>künstlicher Intelligenz [11]</b> zu kommunizieren. Nach ""Mobile first"" stehen wir am Übergang in die Ära der künstlichen Intelligenz, sagt der CEO. Google hat seine künstliche Intelligenz in den vergangenen Jahren weiterentwickelt und hält sie nun für reif genug, auf den Menschen losgelassen zu werden. </p>
<h3 class=""subheading"">Smartphone als Plattform</h3>
<p>Googles Assistent soll zu einem universalen Dienstleister werden, der die verschiedensten Aufgaben für seinen Nutzer erledigen kann. Die Hardware, auf der der Assistent sein Dasein fristet, ist dabei eigentlich egal. Deshalb geht es bei den <b>neuen Pixel-Smartphones [12]</b> auch nicht darum, den Markt von hinten aufzurollen (das dürfte angesichts der Preise, die Google für seine Pixel aufruft, auch schwierig werden). </p>
<p/>
<p>Was das inzwischen eingeschläferte Nexus-Programm für Android war, sind die Pixel und der <b>Wohnzimmerlautsprecher Google Home [13]</b> für den Assistenten: Eine perfekte Bühne. Betriebssysteme und Apps, die das mobile Zeitalter geprägt haben, treten in den Hintergrund und ordnen sich dem Assistenten unter. Der übernimmt zunehmend Funktionen, für die wir bisher verschiedene Apps benutzt haben – oder für die das OS zuständig war. </p>
<h3 class=""subheading"">The Next Big Thing</h3>
<p>Von Android war am Dienstag so auch nur am Rande die Rede. Das ist bemerkenswert für eine Veranstaltung, auf der Google immerhin eigene Smartphones vorgestellt hat.</p>
<p>Mit Android hat Google seine Vormachtstellung in den ""Mobile first""-Jahren unter Schmidt ausgebaut. Pichai setzt jetzt auf künstliche Intelligenz. Der Wettbewerb ist hart: Amazon, Apple, IBM, Microsoft. Jeder, der in der IT-Branche was auf sich hält, forscht an Künstlicher Intelligenz. Mensch-Maschine-Kommunikation ist das nächste ""große Ding"". </p>
<p>



<br class=""clear""/>


</p>
        </div>
        <hr/>
        <p class=""size80"">
            <strong>URL dieses Artikels:</strong><br/>
            https://www.heise.de/newsticker/meldung/Googles-Kuenstliche-Intelligenz-Mobile-first-war-gestern-3341711.html
        </p>
            <p class=""size80"">
                <strong>Links in diesem Artikel:</strong><br/>
                      [1] https://www.heise.de/newsticker/meldung/MWC-Google-setzt-auf-Mobile-first-932486.html<br/>
                      [2] https://www.heise.de/newsticker/meldung/MWC-Jahr-des-Androiden-936129.html<br/>
                      [3] https://www.heise.de/ct/artikel/Das-richtige-Smartphone-fuer-jeden-3231481.html<br/>
                      [4] https://www.heise.de/newsticker/meldung/Google-Pixel-und-Pixel-XL-Android-Smartphones-mit-AI-und-der-besten-Kamera-3340555.html<br/>
                      [5] https://www.heise.de/meldung/Google-bringt-eigenen-Assistenten-in-Lautsprecher-Form-3340689.html<br/>
                      [6] https://www.heise.de/newsticker/meldung/Chromecast-Ultra-4K-Videos-und-verschiedene-HDR-Geschmacksrichtungen-3340676.html<br/>
                      [7] https://www.heise.de/newsticker/meldung/Google-Wifi-der-vollautomatische-Sorglos-Router-3340654.html<br/>
                      [8] https://www.heise.de/newsticker/meldung/Googles-VR-Headset-Daydream-ist-aus-Stoff-und-kostet-69-Euro-3340660.html<br/>
                      [9] https://www.heise.de/meldung/Ausprobiert-Mit-Google-Daydream-macht-Virtual-Reality-viel-mehr-Spass-als-mit-Cardboard-3340770.html<br/>
                      [10] https://www.heise.de/meldung/Die-KI-aus-dem-Netz-Googles-kuenstliche-Intelligenz-als-Zentrum-von-Smartphone-und-Alltagstechnik-3340829.html<br/>
                      [11] https://www.heise.de/newsticker/meldung/Die-KI-aus-dem-Netz-Googles-kuenstliche-Intelligenz-als-Zentrum-von-Smartphone-und-Alltagstechnik-3340829.html<br/>
                      [12] https://www.heise.de/newsticker/meldung/Google-Pixel-und-Pixel-XL-Android-Smartphones-mit-AI-und-der-besten-Kamera-3340555.html<br/>
                      [13] https://www.heise.de/newsticker/meldung/Google-bringt-eigenen-Assistenten-in-Lautsprecher-Form-3340689.html<br/>
                      [14] mailto:vbr@ct.de<br/>
            </p>
    </article></article:body>
"

**Comment by fb87** [comment] 2016-10-08 00:22
`"<!DOCTYPE html SYSTEM ""1.0"">
<article:body><article>
        
        <div class=""meldung_wrapper druckversion"">
            
    
        
    

    
    <figure class=""aufmacherbild"">
            <img src=""/home/frank/.local/share/feedreader/data/images/feed_http:__www.heise.de_newsticker_heise.rdf/tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_157988ba623:cd4ff6:d93b8304/1""/>
            <figcaption>
                <p class=""caption"">CEO Sundar Pichai führt Google in ein neues Zeitalter.</p>
            </figcaption>
    </figure>
    

            
            <p class=""meldung_anrisstext""><strong>Smartphones, Chromecast, Google Home: Die ganze Hardware, die Google vorgestellt hat, ist nur Mittel zum Zweck. Für den Konzern beginnt eine neue Ära: die der Künstlichen Intelligenz.</strong></p>
            <p>In Barcelona gibt Eric Schmidt Googles neue Marschrichtung vor: ""<b>Mobile first [1]</b>"" heißt es nun für den Suchmaschinenkonzern, der mit dem Netz groß geworden ist. Das war im Februar <b>2010 auf dem Mobile World Congress [2]</b>. Der <b>Smartphone-Markt [3]</b> war im Umbruch, HSPA+ der letzte Schrei. Am Abend zuvor hatte Steve Ballmer Microsofts neues Windows Phone vorgestellt und Googles eigenes Mobilbetriebssystem Android sollte wenig später erstmals die 10-Prozent-Hürde bei den Marktanteilen nehmen.</p>
<p>

    

</p>
<h3 class=""subheading"">Googles neuer Weg</h3>
<p>Gut sechs Jahre später ist wieder Zeit für so einen Kurswechsel. Googles CEO heißt heute Sundar Pichai, damals war er im Konzern für Chrome und später auch Android verantwortlich. Als Pichai am Dienstag Googles Launch-Event eröffnet, redet er nicht über neue Smartphones oder Android-Versionen. Pichai spricht vor allem über eins: Den Assistenten. Während die Wettbewerber ihre digitalen Assistenzsysteme mit Namen wie Alexa, Cortana oder Siri vermenscheln, ist es bei Google schlicht der Assistent. </p>
<p>Das Zeitalter des Smartphones geht zu Ende, ist Pichai überzeugt. Es wird künftig nur eins von verschiedenen Mitteln sein, mit <b>künstlicher Intelligenz [11]</b> zu kommunizieren. Nach ""Mobile first"" stehen wir am Übergang in die Ära der künstlichen Intelligenz, sagt der CEO. Google hat seine künstliche Intelligenz in den vergangenen Jahren weiterentwickelt und hält sie nun für reif genug, auf den Menschen losgelassen zu werden. </p>
<h3 class=""subheading"">Smartphone als Plattform</h3>
<p>Googles Assistent soll zu einem universalen Dienstleister werden, der die verschiedensten Aufgaben für seinen Nutzer erledigen kann. Die Hardware, auf der der Assistent sein Dasein fristet, ist dabei eigentlich egal. Deshalb geht es bei den <b>neuen Pixel-Smartphones [12]</b> auch nicht darum, den Markt von hinten aufzurollen (das dürfte angesichts der Preise, die Google für seine Pixel aufruft, auch schwierig werden). </p>
<p/>
<p>Was das inzwischen eingeschläferte Nexus-Programm für Android war, sind die Pixel und der <b>Wohnzimmerlautsprecher Google Home [13]</b> für den Assistenten: Eine perfekte Bühne. Betriebssysteme und Apps, die das mobile Zeitalter geprägt haben, treten in den Hintergrund und ordnen sich dem Assistenten unter. Der übernimmt zunehmend Funktionen, für die wir bisher verschiedene Apps benutzt haben – oder für die das OS zuständig war. </p>
<h3 class=""subheading"">The Next Big Thing</h3>
<p>Von Android war am Dienstag so auch nur am Rande die Rede. Das ist bemerkenswert für eine Veranstaltung, auf der Google immerhin eigene Smartphones vorgestellt hat.</p>
<p>Mit Android hat Google seine Vormachtstellung in den ""Mobile first""-Jahren unter Schmidt ausgebaut. Pichai setzt jetzt auf künstliche Intelligenz. Der Wettbewerb ist hart: Amazon, Apple, IBM, Microsoft. Jeder, der in der IT-Branche was auf sich hält, forscht an Künstlicher Intelligenz. Mensch-Maschine-Kommunikation ist das nächste ""große Ding"". </p>
<p>



<br class=""clear""/>


</p>
        </div>
        <hr/>
        <p class=""size80"">
            <strong>URL dieses Artikels:</strong><br/>
            https://www.heise.de/newsticker/meldung/Googles-Kuenstliche-Intelligenz-Mobile-first-war-gestern-3341711.html
        </p>
            <p class=""size80"">
                <strong>Links in diesem Artikel:</strong><br/>
                      [1] https://www.heise.de/newsticker/meldung/MWC-Google-setzt-auf-Mobile-first-932486.html<br/>
                      [2] https://www.heise.de/newsticker/meldung/MWC-Jahr-des-Androiden-936129.html<br/>
                      [3] https://www.heise.de/ct/artikel/Das-richtige-Smartphone-fuer-jeden-3231481.html<br/>
                      [4] https://www.heise.de/newsticker/meldung/Google-Pixel-und-Pixel-XL-Android-Smartphones-mit-AI-und-der-besten-Kamera-3340555.html<br/>
                      [5] https://www.heise.de/meldung/Google-bringt-eigenen-Assistenten-in-Lautsprecher-Form-3340689.html<br/>
                      [6] https://www.heise.de/newsticker/meldung/Chromecast-Ultra-4K-Videos-und-verschiedene-HDR-Geschmacksrichtungen-3340676.html<br/>
                      [7] https://www.heise.de/newsticker/meldung/Google-Wifi-der-vollautomatische-Sorglos-Router-3340654.html<br/>
                      [8] https://www.heise.de/newsticker/meldung/Googles-VR-Headset-Daydream-ist-aus-Stoff-und-kostet-69-Euro-3340660.html<br/>
                      [9] https://www.heise.de/meldung/Ausprobiert-Mit-Google-Daydream-macht-Virtual-Reality-viel-mehr-Spass-als-mit-Cardboard-3340770.html<br/>
                      [10] https://www.heise.de/meldung/Die-KI-aus-dem-Netz-Googles-kuenstliche-Intelligenz-als-Zentrum-von-Smartphone-und-Alltagstechnik-3340829.html<br/>
                      [11] https://www.heise.de/newsticker/meldung/Die-KI-aus-dem-Netz-Googles-kuenstliche-Intelligenz-als-Zentrum-von-Smartphone-und-Alltagstechnik-3340829.html<br/>
                      [12] https://www.heise.de/newsticker/meldung/Google-Pixel-und-Pixel-XL-Android-Smartphones-mit-AI-und-der-besten-Kamera-3340555.html<br/>
                      [13] https://www.heise.de/newsticker/meldung/Google-bringt-eigenen-Assistenten-in-Lautsprecher-Form-3340689.html<br/>
                      [14] mailto:vbr@ct.de<br/>
            </p>
    </article></article:body>
"`

**Comment by jangernert** [comment] 2016-10-08 14:54
HTML seems fine. But can you give the new 'articleview'-branch a try? ba81e2da6022f51871dba48f8c4c3dad417c0cf3
There I reworked the articleView to destroy the current WebKit.WebView widget and create a completely new widget for every article. Seems like bit of overkill, but maybe it'll help in your situation. At least there should be no problems with the webviews indefinitely loading without being able to be canceled anymore :P

**Comment by fb87** [comment] 2016-10-08 22:12
I did compile and install, but I'm having the issue that the FR logo just shows a placeholder. I already had this issue some time ago, that I was just shown placeholders, but a uninstall & reinstall fixed this – but not in this case. Before I wasn't displayed some(?) feed logos, too. Problem is, it grabs feeds forever. I restarted some hours ago, but it still runs.

• After changing a branch, is it save to install the new version over the older installation? `make uninstall` didn't work, because the list of installed software wasn't created (because of switching to an empty branch).

**Comment by jangernert** [comment] 2016-10-08 22:52
1. You need to log out and back in again. The new "plugin"-key is still set to 0 on your machine.
2. should be save
3. /usr/local/ for system-wide files like plugins or css/html and ~/.local/ for user specific files like feed-icons and the data-base

**Comment by jangernert** [comment] 2016-10-13 13:56
Since the ArticleView has been refactored, and a new WebView is created for every article, this is unlikely to happen again. I'll close this.

**Closed by jangernert** 2016-10-13 13:56 UTC
Labels: bug
