### ISSUE TITLE
Ubuntu 16.10 support

### ISSUE THREAD

**Issue by danielholm** [jangernert/FeedReader#244] opened 2016-10-15 17:08 UTC
Ubuntu 16.10 was released the other day and there is no packages available in the PPA. Packages for Ubuntu 16.04 does not install due to the dependency libwebkit2gtk-3.0-25 not available (available version is ibwebkit2gtk-4.0-37).

**Comment by jangernert** [comment] 2016-10-16 09:45
Duplicate of #243

**Closed by jangernert** 2016-10-16 09:45 UTC
