### ISSUE TITLE
Monospace rendering issue

### ISSUE THREAD

**Issue by lightonflux** [jangernert/FeedReader#68] opened 2016-03-13 10:32 UTC
Article: https://linuxundich.de/gnu-linux/apt-get-apt-cache-laesst-sich-schon-lange-mit-apt-abkuerzen/

Rendering issue for inline monospaced text:

![bildschirmfoto von 2016-03-13 11-31-22](https://cloud.githubusercontent.com/assets/1377943/13728162/3cf52762-e90f-11e5-85ff-e361e15ddd5d.png)

**Comment by bil-elmoussaoui** [comment] 2016-03-13 13:43
Works fine here, which version of FeedReader you're using ? 
![capture du 2016-03-13 14-42-04](https://cloud.githubusercontent.com/assets/7660997/13728993/cfeee962-e929-11e5-86c4-0bbe8f79dcda.png)

**Comment by jangernert** [comment] 2016-03-13 16:38
And which version of wegkitgtk does your system have? Still the old webkitgtk 3.0 ?

**Comment by lightonflux** [comment] 2016-03-13 18:41
webkitgtk 4.0 compiled commit 17cb2641f98baa5ec025c7db3cab911a98620fd5

Changing the feedreader theme (pergament, midnight) does not change the rendering issue. 

Any other infos you need?

**Comment by jangernert** [comment] 2016-03-13 18:45
You can play around with the CSS of the theme "/usr/share/FeedReader/ArticleView/style.css" and see if you can make it work. All FeedReader does is take the html content and the CSS and throw them in a webkit webview together. So it could be a issue with webkit itself.

**Comment by jangernert** [comment] 2016-03-18 22:01
merging this issue with #76:

> I'm using the version from the Software Center on Fedora 23 and I have weird problems with the text, I attached an example from Fedora Magazine.
![screenshot from 2016-03-18 21-43-18](https://cloud.githubusercontent.com/assets/5249239/13890164/bbaa1d3c-ed52-11e5-8caf-8cdf4b07399c.png)
The FeedReader version is 1.4.3

**Comment by jangernert** [comment] 2016-03-18 22:03
Did you guys fiddle with your font-rendering in any way? (infinality or something)

**Comment by lightonflux** [comment] 2016-03-18 23:07
No. Just default rendering in Debian testing. I remember two big changes in font rendering in Debian since Jessie. Will try to find the changelogs.

**Comment by lightonflux** [comment] 2016-03-18 23:14
Time frame reference: https://m.reddit.com/r/debian/comments/3rdwt4/amazing_font_rendering_in_debian_testing/cwncjdz

**Comment by jangernert** [comment] 2016-03-18 23:56
You can try and replace the CSS file with a new empty one to see if its related to the CSS FeedReader is using
"/usr/share/FeedReader/ArticleView/style.css"
If not it has to have something to do with the font-rendering on your system or webkit. At least I don't know what FeedReader could have to do with this issue =/

**Comment by lightonflux** [comment] 2016-03-19 00:01
![bildschirmfoto von 2016-03-19 00-58-10](https://cloud.githubusercontent.com/assets/1377943/13894937/b0cbe40c-ed6d-11e5-811d-85cec33e6532.png)

So not a FeedReader problem then. But whose problem is it?

@yotamN what is your exact webkitgtk and freetype version?


For me:
 * libwebkit2gtk-4.0-dev → 2.10.8-1
 * libfreetype6 → 2.6.3-3

**Comment by jangernert** [comment] 2016-03-19 00:17
I wrote a small demo application to test some things related to the ArticleView. Maybe it could be of help in this case as well?
[WebKit-DEMO.zip](https://github.com/jangernert/FeedReader/files/180563/WebKit-DEMO.zip)
It is basically just a WebKit webview that puts together HTML code you drop in the left pane and puts together an article with a few extra lines of HTML and the CSS code.

**Comment by lightonflux** [comment] 2016-03-19 00:29
Quick test, still the same result. (Don't be confused by the font, was just testing if webkit ignores certain font settings, and it does).

![bildschirmfoto von 2016-03-19 01-28-20](https://cloud.githubusercontent.com/assets/1377943/13895300/e61ae5be-ed71-11e5-8b85-da124d0acd18.png)

**Comment by jangernert** [comment] 2016-03-19 00:37
I guess you will still have the issue without CSS here, right?
You could test if some of the settings I used with WebKit are not working for you, like "set_enable_accelerated_2d_canvas" in the "WebKit.vala" file. Other than that I am pretty much out of ideas.

**Comment by bil-elmoussaoui** [comment] 2016-03-22 22:53
I will try to install Debian on a virtual machine and see if i can reproduce this issue and try to find a way to fix it even if i think it's just a missing font

**Comment by yotamN** [comment] 2016-03-23 10:10
@bil-elmoussaoui It also happened on Fedora 23 for me

**Comment by jangernert** [comment] 2016-05-03 01:02
This is what it looks like on a fresh Fedora 24 vm
![screenshot from 2016-05-03 03-00-36](https://cloud.githubusercontent.com/assets/12012494/14972363/635f1568-10db-11e6-866a-df060ef1da3e.png)

**Comment by bil-elmoussaoui** [comment] 2016-05-09 11:49
I really can't reporduce this :( can you update the font cache and try again?

**Comment by lightonflux** [comment] 2016-05-09 23:27
Updated the font cache several times. Just now after the last comment (with newest dev version). And back when i tried the theming app on March 19.

      fc-cache -fv  # and restarting feedreader and the OS

Does not change a thing.

**Comment by bil-elmoussaoui** [comment] 2016-06-05 13:19
I pushed a commit that should fix that! + added other fonts to `font-familly` instead of using only `monospace`. If it's not fixed for you, feel free to report back/repon this

**Comment by lightonflux** [comment] 2016-06-05 17:21
Tested with Debian Testing. 

>Version: 1.6 beta
> Git Commit: 74f73dd05ac4ed9d339dadc966ee2f7b8cec6d10

I did not change the font and anything, just updated. 

Image:

![bildschirmfoto von 2016-06-05 19-19-39](https://cloud.githubusercontent.com/assets/1377943/15807029/8ae7fb18-2b52-11e6-9721-19b1f70f3f5b.png)

**Comment by bil-elmoussaoui** [comment] 2016-06-05 17:23
I'm out of ideas :( can you try reading your article on a browser that uses Webkit like Epiphany?

**Comment by bil-elmoussaoui** [comment] 2016-06-05 17:31
I just took a look at the source code of the website and they use code directly instead of using pre tag. I pushed a new fix, i think it should be fixed (at least if i can do something about it :P)

**Comment by lightonflux** [comment] 2016-06-05 22:54
I would like to bring you good news...

> Version: 1.6 beta
> Git Commit: 65a910e34e19d6ec310b54226da4a4b3a1ebbda5
![bildschirmfoto von 2016-06-06 00-48-13](https://cloud.githubusercontent.com/assets/1377943/15808765/6eb18fa8-2b80-11e6-8460-72d273e07695.png)


At this point i think we can assume it is an upstream bug somewhere. Thank you very much for your work. :+1:

**Comment by bil-elmoussaoui** [comment] 2016-06-05 23:38
I will keep this open. It's might be a missing package/font that should be installed on your system!

**Closed** 2016-07-30 01:42 UTC
Labels: bug
