### ISSUE TITLE
Nullpointer SIGSEV after start

### ISSUE THREAD

**Issue by ente76** [jangernert/FeedReader#677] opened 2018-05-09 06:17 UTC
Starting feedreader --verbose gives:
```
feedreader-INFO: 08:07:00.583: FeedReader 2.2-dev
(feedreader:7810): Gtk-DEBUG: 08:07:00.602: Connecting to session manager
(feedreader:7810): feedreader-DEBUG: 08:07:00.721: MainWindow: setupCSS
(feedreader:7810): feedreader-DEBUG: 08:07:00.724: backend: constructor
(feedreader:7810): feedreader-DEBUG: 08:07:00.724: backend: new FeedServer and login
(feedreader:7810): feedreader-DEBUG: 08:07:00.724: feedserver: engine load Nextcloud News
(feedreader:7810): feedreader-DEBUG: 08:07:00.725: feedserver: plugin loaded Nextcloud News
(feedreader:7810): feedreader-DEBUG: 08:07:00.736: Opening Database: /home/ente/.local/share/feedreader/data/feedreader-6.db
feedreader-INFO: 08:07:00.737: Plugin Name: Nextcloud News
feedreader-INFO: 08:07:00.737: Plugin Version: 0.1
feedreader-INFO: 08:07:00.737: Plugin Website: http://jangernert.github.io/FeedReader/
feedreader-INFO: 08:07:00.737: Plugin Dir: /usr/lib/FeedReader/plugins/
(feedreader:7810): feedreader-DEBUG: 08:07:00.737: Nextcloud: login
(feedreader:7810): feedreader-DEBUG: 08:07:00.737: Nextcloud URL: https://cloud.domain.tld/index.php/apps/news/api/v1-2/
(feedreader:7810): feedreader-DEBUG: 08:07:00.739: Nextcloud URL: https://cloud.domain.tld/index.php/apps/news/api/v1-2/
(feedreader:7810): feedreader-DEBUG: 08:07:00.739: https://cloud.domain.tld/index.php/apps/news/api/v1-2/status
feedreader-INFO: 08:07:01.051: Nextcloud version: 12.0.1
(feedreader:7810): feedreader-DEBUG: 08:07:01.051: backend: login status = FEED_READER_LOGIN_RESPONSE_SUCCESS
(feedreader:7810): feedreader-DEBUG: 08:07:01.056: LoginPage: add plugin owncloud
(feedreader:7810): feedreader-DEBUG: 08:07:01.070: ColumnView: setup
(feedreader:7810): feedreader-DEBUG: 08:07:01.094: HeaderBar: showArticleButtons true
(feedreader:7810): feedreader-DEBUG: 08:07:01.095: UpdateButton: update status
(feedreader:7810): feedreader-DEBUG: 08:07:01.095: UpdateButton: setSensitive true
(feedreader:7810): feedreader-DEBUG: 08:07:01.105: MainWindow: maximize
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: MainWindow: determining state
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: MainWindow: load content
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: MainWindow: show content
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: FeedList: new FeedList
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: backend: symbolicIcon
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: feedserver: symbolicIcon
(feedreader:7810): feedreader-DEBUG: 08:07:01.139: Nextcloud URL: https://cloud.domain.tld/index.php/apps/news/api/v1-2/
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

    #1  <unknown>   in 'vilistextum'
        at feedreader
    #2  <unknown>   in 'feed_reader_utils_UTF8fix'
        at feedreader
    #3  <unknown>   in 'feed_reader_feed_construct'
        at feedreader
    #4  <unknown>   in 'feed_reader_feed_new'
        at feedreader
    #5  <unknown>   in 'feed_reader_data_base_read_only_read_feeds'
        at feedreader
    #6  <unknown>   in 'feed_reader_feed_list_newFeedlist'
        at feedreader
    #7  <unknown>   in 'feed_reader_main_window_showContent'
        at feedreader
    #8  <unknown>   in 'feed_reader_main_window_get_default'
        at feedreader
    #9  <unknown>   in 'g_closure_invoke'
        at /usr/lib/libgobject-2.0.so.0
    ...
```

During that startup on the server I get a sequence as follows:
```
Info | Login successful: "user@domain.tld" | a minute ago
-- | -- | --
Info | Login attempt: "user@domain.tld" | a minute ago
Info | Logout occurred | a minute ago
Info | Login successful: "user@domain.tld" | a minute ago
Info | Login attempt: "user@domain.tld" | a minute ago
```

steps to fix the error: delete ~/.local/share/feedreader/data/*

that allows to start feedreader. sometimes the next sync crashes the feedreader immediately with the same error. in that case, deleting the credentials in seahorse might help. In seahorse the credentials for nextcloud client app are stored as well.

**Comment by ente76** [comment] 2018-05-09 06:17
Version: 2.2-dev
Git Commit: 78d7ced862aa491d64d9b5f135b2ba2d893b79d1

Arch linux - up to date

**Comment by brendanlong** [comment] 2018-05-09 13:26
This error was fixed in 9432e0e2292274d5c13363c1d07a7bc10527a288. Can you try the latest git? We did a new release a few days ago so hopefully this should make it into distro packages soon too.

**Comment by ente76** [comment] 2018-05-20 22:08
I am using a git version for a week now: 
- Version: 2.4-dev
- Git Commit: 1e2015e91df47af89bdcad8f33d16cde2381d0d2

It works perfectly against the nextcloud news as mentioned in my previous error message.

**Comment by Stunkymonkey** [comment] 2018-05-29 19:41
having a simillar problem (current git-version 9120b3418e33ee3c02ab155f7524b2b67c624514) with ttrss:
```
(feedreader:10992): feedreader-DEBUG: 21:26:32.357: ttrss URL: https://feeds.domain.de/api/
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

    #1  <unknown>   in 'feed_reader_utils_UTF8fix'
        at /usr/lib/libFeedReader.so
    #2  <unknown>   in 'feed_reader_feed_construct'
        at /usr/lib/libFeedReader.so
    #3  <unknown>   in 'feed_reader_feed_new'
        at /usr/lib/libFeedReader.so
    #4  <unknown>   in 'feed_reader_feed_list_newFeedlist'
        at /usr/lib/libFeedReader.so
    #5  <unknown>   in 'feed_reader_main_window_showContent'
        at /usr/lib/libFeedReader.so
    #6  <unknown>   in 'feed_reader_main_window_get_default'
        at /usr/lib/libFeedReader.so
    #7  <unknown>   in 'g_closure_invoke'
        at /usr/lib/libgobject-2.0.so.0
    #8  <unknown>   in 'g_signal_emit_valist'
        at /usr/lib/libgobject-2.0.so.0
    #9  <unknown>   in 'g_signal_emit'
        at /usr/lib/libgobject-2.0.so.0
    #10  <unknown>   in 'ffi_call_unix64'
        at /usr/lib/libffi.so.6
    #11  <unknown>   in 'ffi_call'
        at /usr/lib/libffi.so.6
    #12  <unknown>   in 'g_cclosure_marshal_generic_va'
        at /usr/lib/libgobject-2.0.so.0
    #13  <unknown>   in 'g_signal_emit_valist'
        at /usr/lib/libgobject-2.0.so.0
    #14  <unknown>   in 'g_signal_emit'
        at /usr/lib/libgobject-2.0.so.0
    #15  <unknown>   in 'g_application_run'
        at /usr/lib/libgio-2.0.so.0
    #16  <unknown>   in 'feed_reader_main_main'
        at feedreader
    #17  <unknown>   in '__libc_start_main'
        at 
    #18  <unknown>   in '_start'
        at feedreader
```

**Comment by Stunkymonkey** [comment] 2018-06-15 23:03
i did a bisec:
works with this one 9fdc62082b4ef458ed28105fded69af9df046a9b,
but seg faults with the next one: b5ab26de2928e011ceafeb87e0f20131764e7021

**Comment by Stunkymonkey** [comment] 2018-06-16 16:49
![image](https://user-images.githubusercontent.com/1315818/41500612-5110fe18-7195-11e8-856a-7394a953e753.png)

this is the only weird thing, but may be related to your commit
everything else works fine

**Comment by ente76** [comment] 2018-07-06 06:44
I used 
    Version: 2.4-dev
    Git Commit: 1e2015e
for almost 3 month. No Error. No Problem. Perfectly fine.

Arch Linux updated the official package to
    Version: 2.2-dev
    Git Commit: 8d79eb6da717afdfc5a5287b7eb445c8176c6ed0
This version of feedreader is unusable for nc-news. The following problems occur:
1. mixxed headers
2. messed up symbols in headers
3. articles with messed up symbols can't be opened at all
4. version crashed on start up

I am reverting to Git Commit: 1e2015e.

Below some screenshots.
article can't be loaded; header has cryptic symbols
![image](https://user-images.githubusercontent.com/3661860/42363035-3193e062-80f6-11e8-9195-2e056ef3c345.png)

header is messed up. Original header ends at "Vega-Grafik". The rest does not belong to this article.
![image](https://user-images.githubusercontent.com/3661860/42363064-4b13971c-80f6-11e8-8c44-94fc270f96fe.png)

Below some errors shown in verbose mode, that may be related: 
(feedreader:9811): feedreader-DEBUG: 08:14:07.236: FeedReader: newFeedList
(feedreader:9811): feedreader-DEBUG: 08:14:07.236: FeedList: new FeedList
(feedreader:9811): feedreader-DEBUG: 08:14:07.237: backend: symbolicIcon
(feedreader:9811): feedreader-DEBUG: 08:14:07.237: feedserver: symbolicIcon
(feedreader:9811): feedreader-DEBUG: 08:14:07.237: Nextcloud URL: https://cloud.domain.tld/index.php/apps/news/api/v1-2/
(feedreader:9811): feedreader-DEBUG: 08:14:07.237: https://cloud.domain.tld/index.php/apps/news/api/v1-2/items?oldestFirst=false&type=2&getRead=true&id=0&offset=0&batchSize=-1
read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
213 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 (feedreader:9811): feedreader-DEBUG: 08:14:07.245: FeedList: no tags

(feedreader:9811): Pango-WARNING **: 08:14:07.259: Invalid UTF-8 string passed to pango_layout_set_text()

(feedreader:9811): Pango-WARNING **: 08:14:07.269: Invalid UTF-8 string passed to pango_layout_set_text()

(feedreader:9811): Pango-WARNING **: 08:14:07.273: Invalid UTF-8 string passed to pango_layout_set_text()

(feedreader:9811): Pango-WARNING **: 08:14:07.281: Invalid UTF-8 string passed to pango_layout_set_text()
(feedreader:9811): feedreader-DEBUG: 08:14:07.282: initCollapseCategories
(feedreader:9811): feedreader-DEBUG: 08:14:07.282: FeedList.restoreSelectedRow: feed -76


later in the same log:
(feedreader:9811): feedreader-CRITICAL **: 08:14:07.541: FavIcon.load: Alternativlos - Compressed icons are not supported
(feedreader:9811): feedreader-DEBUG: 08:14:11.042: getArticles: 21 articles returned
(feedreader:9811): feedreader-DEBUG: 08:14:11.058: FeedReader: refreshFeedListCounter
read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
213 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 (feedreader:9811): feedreader-DEBUG: 08:14:11.063: FeedReader: updateArticleList
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: ArticleList: updateArticleList()
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: ArticleList: updateArticleList(): emtpy list -> create newList()
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: ArticleList: newList
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: ArticleList: disallow signals from scroll
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: load articles from db
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: actual articles loaded: 0
(feedreader:9811): feedreader-DEBUG: 08:14:11.063: ArticleList: no content, so allow signals from scroll again
(feedreader:9811): feedreader-DEBUG: 08:14:11.068: FeedReader: refreshFeedListCounter
read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
213 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 (feedreader:9811): feedreader-DEBUG: 08:14:11.074: FeedReader: updateArticleList
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: ArticleList: updateArticleList()
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: ArticleList: updateArticleList(): emtpy list -> create newList()
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: ArticleList: newList
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: ArticleList: disallow signals from scroll
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: load articles from db
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: actual articles loaded: 0
(feedreader:9811): feedreader-DEBUG: 08:14:11.075: ArticleList: no content, so allow signals from scroll again
(feedreader:9811): feedreader-DEBUG: 08:14:11.081: FeedReader: refreshFeedListCounter
read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
213 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 (feedreader:9811): feedreader-DEBUG: 08:14:11.087: FeedReader: updateArticleList
(feedreader:9811): feedreader-DEBUG: 08:14:11.087: ArticleList: updateArticleList()
(feedreader:9811): feedreader-DEBUG: 08:14:11.087: ArticleList: updateArticleList(): emtpy list -> create newList()
(feedreader:9811): feedreader-DEBUG: 08:14:11.087: ArticleList: newList
(feedreader:9811): feedreader-DEBUG: 08:14:11.087: ArticleList: disallow signals from scroll
(feedreader:9811): feedreader-DEBUG: 08:14:11.088: load articles from db
(feedreader:9811): feedreader-DEBUG: 08:14:11.088: actual articles loaded: 0
(feedreader:9811): feedreader-DEBUG: 08:14:11.088: ArticleList: no content, so allow signals from scroll again
(feedreader:9811): feedreader-DEBUG: 08:14:11.092: FeedReader: refreshFeedListCounter
read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 (feedreader:9811): feedreader-DEBUG: 08:14:11.092: https://cloud.domain.tld/index.php/apps/news/api/v1-2/items?oldestFirst=false&type=3&getRead=false&id=0&offset=0&batchSize=-1
read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
213 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 read_char: errno==EILSEQ; invalid byte sequence for utf-8: 
212 (feedreader:9811): feedreader-DEBUG: 08:14:11.095: FeedReader: updateArticleList


further down:
(feedreader:9811): feedreader-DEBUG: 08:21:07.043: feedserver: symbolicIcon
(feedreader:9811): feedreader-DEBUG: 08:21:07.044: Nextcloud URL: https://cloud.domain.tld/index.php/apps/news/api/v1-2/
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
(feedreader:9811): feedreader-DEBUG: 08:21:07.054: FeedList: no tags

(feedreader:9811): Pango-WARNING **: 08:21:07.064: Invalid UTF-8 string passed to pango_layout_set_text()

(feedreader:9811): Pango-WARNING **: 08:21:07.068: Invalid UTF-8 string passed to pango_layout_set_text()
(feedreader:9811): feedreader-DEBUG: 08:21:07.081: initCollapseCategories
(feedreader:9811): feedreader-DEBUG: 08:21:07.082: FeedList.restoreSelectedRow: feed -76
(feedreader:9811): feedreader-DEBUG: 08:21:07.082: FeedReader: syncFinished
(feedreader:9811): feedreader-DEBUG: 08:21:07.082: MainWindow: show content
(feedreader:9811): feedreader-DEBUG: 08:21:07.082: HeaderBar: setButtonsSensitive true
(feedreader:9811): feedreader-DEBUG: 08:21:07.082: UpdateButton: setSensitive true
(feedreader:9811): feedreader-DEBUG: 08:21:07.093: UpdateButton: update status

(feedreader:9811): Gtk-WARNING **: 08:23:32.218: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:23:32.317: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:23:32.334: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:23:32.618: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'
(feedreader:9811): feedreader-DEBUG: 08:23:32.937: ArticleView: load article 20854
(feedreader:9811): feedreader-DEBUG: 08:23:32.937: HeaderBar: showArticleButtons true
(feedreader:9811): feedreader-DEBUG: 08:23:32.937: DataBaseReadOnly.read_article(): 20854
(feedreader:9811): feedreader-DEBUG: 08:23:32.938: ContentPage: set headerbar
(feedreader:9811): feedreader-DEBUG: 08:23:32.941: FeedReader: refreshFeedListCounter
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �


more to come:
(feedreader:9811): feedreader-DEBUG: 08:26:11.392: ArticleView: loading 100 %
(feedreader:9811): feedreader-DEBUG: 08:26:11.392: ArticleView: load FINISHED

(feedreader:9811): Pango-WARNING **: 08:26:11.400: Invalid UTF-8 string passed to pango_layout_set_text()

(feedreader:9811): Gtk-WARNING **: 08:26:11.718: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.737: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.752: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.770: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.786: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.802: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.820: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'

(feedreader:9811): Gtk-WARNING **: 08:26:11.833: Failed to set text 'Klimaerwärmung P\x8d&#x17;vhU' from markup due to error parsing markup: Error on line 1 char 36: Invalid UTF-8 encoded text in name - not valid 'Klimaerwärmung P\x8d\u0017vhU'
(feedreader:9811): feedreader-DEBUG: 08:26:13.222: ArticleView: load article 20853
(feedreader:9811): feedreader-DEBUG: 08:26:13.222: HeaderBar: showArticleButtons true
(feedreader:9811): feedreader-DEBUG: 08:26:13.222: DataBaseReadOnly.read_article(): 20853


if an article can't be loaded, log shows (those are all lines from clicking article to failed state):
(feedreader:15791): feedreader-DEBUG: 08:41:41.177: ArticleView: load article 20774
(feedreader:15791): feedreader-DEBUG: 08:41:41.177: HeaderBar: showArticleButtons true
(feedreader:15791): feedreader-DEBUG: 08:41:41.177: DataBaseReadOnly.read_article(): 20774
(feedreader:15791): feedreader-DEBUG: 08:41:41.177: ContentPage: set headerbar
(feedreader:15791): feedreader-DEBUG: 08:41:41.180: FeedReader: refreshFeedListCounter
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
read_char: errno==EILSEQ; invalid byte sequence for utf-8: �
(feedreader:15791): feedreader-DEBUG: 08:41:41.187: ArticleView: WebView load html
(feedreader:15791): feedreader-DEBUG: 08:41:41.187: ArticleView: view1 -> view2
(feedreader:15791): feedreader-DEBUG: 08:41:41.188: ArticleView: loading 10 %
(feedreader:15791): feedreader-DEBUG: 08:41:41.199: ArticleView: Policy decision
(feedreader:15791): feedreader-DEBUG: 08:41:41.199: WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION
(feedreader:15791): feedreader-DEBUG: 08:41:41.200: ArticleView: load STARTED
(feedreader:15791): feedreader-DEBUG: 08:41:41.200: ArticleView: load COMMITTED
(feedreader:15791): feedreader-DEBUG: 08:41:41.201: ArticleView: loading 100 %
(feedreader:15791): feedreader-DEBUG: 08:41:41.201: ArticleView: load FINISHED

(feedreader:15791): Json-CRITICAL **: 08:41:41.398: json_node_get_object: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed

**Comment by brendanlong** [comment] 2018-07-06 14:38
@ente76 It sounds like Arch updated to an older version? You should definitely use 2.4-dev not 2.2-dev.

**Comment by brendanlong** [comment] 2018-07-09 16:06
Can I get an example of a feed that causes this?

**Comment by City-busz** [comment] 2018-07-09 20:56
Every added feeds cause this crash with the local RSS backend.

**Comment by brendanlong** [comment] 2018-07-10 14:59
I can't reproduce this on the latest git commit:

![screenshot from 2018-07-10 10-47-01](https://user-images.githubusercontent.com/1447206/42517866-b5d38f04-842e-11e8-8f6f-0116915a414b.png)

I intentionally picked a German feed but it seems to be working fine :(

**Comment by brendanlong** [comment] 2018-07-14 13:59
I have no idea what's going wrong but I reverted b5ab26de2928e011ceafeb87e0f20131764e7021.

I assume this is some weird build system think interacting with C code and different locales? Anyway, please try the latest commit on master and let me know if you still see this.

**Closed by brendanlong** 2018-07-14 13:59 UTC
Labels: bug

**Comment by ente76** [comment] 2018-07-14 16:11
I uninstalled the official Arch Linux version and installed the git-Version 8 days ago. I am running on 
- Version: 2.4-dev
- Git Commit: 8d79eb6da717afdfc5a5287b7eb445c8176c6ed0
for a week now. No Problems. No errors at all. The coding error on the arch linux version occurred on all feeds. Most of my feeds are in English. System language and coding is English. I assume the Arch version is kinda damaged. I will contact the package maintainer.

**Comment by brendanlong** [comment] 2018-07-14 21:55
Oh so maybe it's just an Arch issue? :\

**Comment by City-busz** [comment] 2018-07-19 07:46
I confirm that commit https://github.com/jangernert/FeedReader/commit/33c73c63e34b21478ed00995255404ac73c60b4a fixes the problem on Arch Linux.
