### ISSUE TITLE
Garbled text for feed names and content (latest master)

### ISSUE THREAD

**Issue by Gert-dev** [jangernert/FeedReader#331] opened 2017-01-23 16:31 UTC
Hello

I'm creating this issue as per your request in [this ticket](https://github.com/jangernert/FeedReader/issues/324#issuecomment-274370166).

For quick reference:

> I'm now running into another problem that I did not have before, namely that all my feed names and
> the contents of feed articles contain garbled Unicode characters, e.g. `Gaming On Linux LL `. > However, I don't recall this happening in 2.0 beta 1, so that may be another issue entirely.
>
> ![screenshot](https://cloud.githubusercontent.com/assets/24809863/22072595/1f8825c4-dda3-11e6-9a1a-19aa5e728230.png)

The culprit seems to be 1d3f1d3. Rolling that back fixes the issue.

Thanks in advance

**Comment by jangernert** [comment] 2017-01-23 18:02
And again, here is the library with a simple make-file for you to test:
[test.zip](https://github.com/jangernert/FeedReader/files/724509/test.zip)
You can just unzip it cd to the directory and 'make'
test.vala just defines some strings (the html-code) and calls the library.
As you already know the critical code to your issue is in fileio.c in open_files() and output_string().
The first is called at the beginning and the second every time a line is parsed and written to the OUTPUT-buffer ;)
Without being able to reproduce the issue all I'm able to do are wild guesses =/

**Comment by Gert-dev** [comment] 2017-01-23 20:24
I've taken a look at the code, but can't reproduce it by simply dropping the bugged out text from the feed into a test variable.

I want to say that it is somehow the way that the Vala side is calling the code, but that doesn't make much sense, seeing as all that was added was the growing of the output buffer. It only seems to happen in the GUI. Does the GUI perhaps pull the content in a specific encoding that is then passed to the C side?

Could you tell me why the buffer growing was added, i.e. when it is triggered? That might help reproducing it - manually causing it to happen in the C test doesn't trigger the issue either.

**Comment by jangernert** [comment] 2017-01-23 21:22
I'm guessing the error happens before you see encoding issues. At some point something goes wrong with the buffer and it overflows. And you shouldn't parse the corrupted text but the raw html/text you get from the feeds.
It was added because the static size was just a hack. It was way too big and even then in some rare incidents it could still overflow.

**Comment by Gert-dev** [comment] 2017-01-24 16:15
That was what I was testing. I tried dropping in some of the text that goes corrupt, but the text itself goes in and comes out fine. It also happens to pretty much everything in the GUI: names as well feed contents. Just using the code as is, the buffer never grows, because the size allocated is always enough. When I manually force the buffer to grow by making the initiial size too small, it also continues working just fine.

**Comment by Gert-dev** [comment] 2017-01-24 16:19
And... in the most recent master, it seems to be fixed. _Very_ strange.

**Comment by jangernert** [comment] 2017-01-24 18:32
I grew the buffer-size by 1 wide char to accommodate the tailing '\0'
Maybe that's what fixed it for you as well.
Most of the time buffer is big enough. But sometimes there are multibyte-chars that need more space. Or so I think. I didn't write the code. So could be I misinterpreted some things :P 
But since it seems to be fixed I'll close this.

**Closed by jangernert** 2017-01-24 18:32 UTC
