### ISSUE TITLE
Crash in random times

### ISSUE THREAD

**Issue by gavr123456789** [jangernert/FeedReader#826] opened 2019-01-05 21:52 UTC
I can not understand the reason for the departure, but the application does not work longer than 3 minutes.
Logs:
https://pastebin.com/er4mFgUF

**Comment by brendanlong** [comment] 2019-01-29 21:42
I made a major change in #843 to try to address crashes like this. Can you check if you get this error in the latest (v2.7.0)?

**Comment by brendanlong** [comment] 2019-02-05 23:52
I think this was caused by the shared non-threadsafe database connections that were fixed in #843. Please let us know if you see any other problems with the latest release.

**Closed by brendanlong** 2019-02-05 23:52 UTC
Labels: bug
