### ISSUE TITLE
Make Feedreader responsive design (adaptative windows)

### ISSUE THREAD

**Issue by prog-amateur** [jangernert/FeedReader#963] opened 2019-11-16 17:44 UTC
Hello, I use a Surface Pro (but this can be possible on "yoga"-like devices, or Librem/Pinephone smartphones) and I have found that Feedreader does fill well the screen. 

**Bug :** 
In portrait mode, the windows is half visible (half left side - with RSS news sources - is visible, while half right side (news article content) is off-screen. Then randomly, the window resize itself and become half vertical/half horizontal. 

Could you please check how to improve the windows behavior and make it responsive design ? 
Thank you very much.

**Comment by bilelmoussaoui** [comment] 2019-11-16 17:47
Duplicate of #771

**Closed by bilelmoussaoui** 2019-11-16 17:47 UTC
Labels: duplicate
