### ISSUE TITLE
Support export of feeds?

### ISSUE THREAD

**Issue by pjmp** [jangernert/FeedReader#940] opened 2019-09-03 05:13 UTC
Hey, thank you for this awesome software! I was wondering if you would consider supporting exporting of feeds as OPML considering the fact that this software already supports importing them.

Thanks!

**Comment by bilelmoussaoui** [comment] 2019-09-03 10:06
Duplicate of https://github.com/jangernert/FeedReader/issues/334

**Closed by bilelmoussaoui** 2019-09-03 10:06 UTC
Labels: duplicate
