### ISSUE TITLE
Always OFFLINE

### ISSUE THREAD

**Issue by sharifzadesina** [jangernert/FeedReader#469] opened 2017-04-24 17:47 UTC
Hi

As expected the issue #426 occurred again and there is no way to solve it except with `Change Account` option.

I am using last stable version this time (!), 2.0.2.

![screenshot from 2017-04-24 22-20-54](https://cloud.githubusercontent.com/assets/15300551/25350948/1ca01d82-293c-11e7-844e-8342a07df157.png)

**Comment by brendanlong** [comment] 2017-04-24 17:51
Based on the logs from #426 I wonder if we're not properly refreshing the Feedly login token / showing the login page when it expires?

**Comment by sharifzadesina** [comment] 2017-04-24 17:53
@brendanlong It seems you are not refreshing, and yes there is no login page, I thin there is no need for login page if they are providing refresh token for their authentication.

**Comment by sharifzadesina** [comment] 2017-04-24 18:36
Hi again,
There are two error in daemons log file:
```
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: plugin removed feedly
[ DEBUG ] count 6
[ DEBUG ] feedserver: engine unload feedly
[ DEBUG ] feedserver: load plugin "feedly"
[ DEBUG ] feedserver: engine load feedly
[ DEBUG ] feedly backend: login
[ DEBUG ] Ping: http://feedly.com/
[ DEBUG ] Ping: status 200
[ DEBUG ] Ping successfull
[ ERROR ] Feedly: getToken response - missing code
[ DEBUG ] refresh token
[ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
```

**Comment by bil-elmoussaoui** [comment] 2017-04-24 18:47
@sharifzadesina What's the output of 
```bash
gsettings get org.gnome.feedreader.feedly api-code
```

**Comment by sharifzadesina** [comment] 2017-04-24 18:48
@bil-elmoussaoui 
Empty!
![screenshot from 2017-04-24 23-20-01](https://cloud.githubusercontent.com/assets/15300551/25353405/5cabec78-2944-11e7-93f6-2e2ce2629744.png)

**Comment by jangernert** [comment] 2017-04-24 18:49
Can you please open up dconf-editor and navigate to org->gnome->feedreader->feedly and check if the fields `access-token`, `access-token-expires` and `refresh-token` aren't empty?
If they are empty it would be helpful if you could reset the account and provide the log of the daemon AND the UI while logging in.

**Comment by sharifzadesina** [comment] 2017-04-24 18:51
@jangernert 
Refresh token is empty.
![screenshot from 2017-04-24 23-21-59](https://cloud.githubusercontent.com/assets/15300551/25353493/a5935b06-2944-11e7-9f87-ddeeaccdd8b2.png)

**Comment by jangernert** [comment] 2017-04-24 19:01
It seems you still have some old settings laying around from pre-plugin times. This shouldn't cause any issue. Just wanting to notice that you can delete them with
```
gsettings reset org.gnome.feedreader.feedly feedly-access-token
gsettings reset org.gnome.feedreader.feedly feedly-api-code
gsettings reset org.gnome.feedreader.feedly feedly-refresh-token
```

I would like to know if the values are never getting written to the settings or if they disappear for some reason afterwards. Could you keep dconf-editor open and log into your account again? Do the settings get written or are they staying empty? While doing that you could also post the logs of the process :)

**Comment by sharifzadesina** [comment] 2017-04-24 19:27
@jangernert 

The values are now filled.

But about log files, the values of them removed after closing the app!

**Comment by jangernert** [comment] 2017-04-24 19:31
> But about log files, the values of them removed after closing the app!

Can you go into more detail? The value of the log files are removed after closing the app? Or the value of the feedly settings?

**Comment by sharifzadesina** [comment] 2017-04-24 19:33
@jangernert no the values of the log files, values of the feeldy settings are ok now.
![screenshot from 2017-04-25 00-04-20](https://cloud.githubusercontent.com/assets/15300551/25355073/a888118e-294a-11e7-9d5f-d36ee5b11762.png)

**Comment by jangernert** [comment] 2017-04-24 19:36
The log files get reset each start of the application (deamon and ui separately). Otherwise you would end up with GB of logs after some time :D IMO the easiest way to get the logs is to kill the running daemon and start `feedreader-daemon`and `feedreader` from shell

**Comment by sharifzadesina** [comment] 2017-04-24 19:38
@jangernert I didn't know that they will remove after closing the app, sorry :D

**Comment by jangernert** [comment] 2017-04-24 19:39
Let's hope the bug will trigger again then :D

**Comment by sharifzadesina** [comment] 2017-04-24 19:43
@jangernert 
Come on man, I think there wasn't anything interested in log files :D
Can you review your codes? :P

**Closed** 2017-05-01 17:31 UTC

**Comment by sharifzadesina** [comment] 2017-05-02 19:24
@jangernert Hi, I have same problem now again, have you fixed it or you just closed the issue?!

**Comment by jangernert** [comment] 2017-05-02 19:31
As you can see in the commit I added logging to all the code dealing with gsettings. If you can exactly tell me at what point your keys and tokens disappear, I might be able to fix the issue. Also your last statement was that everything is okay now.

**Comment by sharifzadesina** [comment] 2017-05-02 19:40
@jangernert 
I told you I have used the `Change Account` option. but the problem occurred again and now I am OFFLINE.
How really can I tell you when the app is in running faze always and the log files get reset after each restart?
Anyway we all know that we can't get this by logs, I am also a programmer and I know that this is impossible, cause if even we find the first point of reading from empty setting, we can't identify which statement causes it.
The only way is reviewing the codes and checking all write operations to `gsettings`.

**Comment by bil-elmoussaoui** [comment] 2017-05-02 19:52
@sharifzadesina Or just run feedreader & feedreader-daemon from terminal whenever you run the application and you can have the logs whenever you have this issue. I'm also using Feedly with the latest commit and i don't have this issue myself. I would like to take a look at the code but if i can't reproduce it i won't be able to correctly track down the issue...

**Comment by jangernert** [comment] 2017-05-02 19:53
Well then **suprise**, that's what I did. As soon as there is a write to gsettings with an empty string or the key is reset there is a warning now.

**Comment by sharifzadesina** [comment] 2017-05-02 19:56
@bil-elmoussaoui 
Ok! but I am not the first/only one who has this problem.
Anyway! I can run both feedreader & feedreader-daemon from terminal but there is some pint here!!!
1- This problem doesn't happen always!!! how long I should wait for it or stay? 1 week?
2- Ok! we have found the warning for empty string! how we can know which statement causes it?

**Comment by hadess** [comment] 2017-07-05 08:34
I'm seeing this now, without having made any changes to the FeedReader configuration. I use the current stable Flatpak.

```
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] feedly backend: login
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] Ping: http://feedly.com/
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] Ping: status 200
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] Ping successfull
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ ERROR ] Feedly: getToken response - missing code
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] refresh token
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
```

**Comment by hadess** [comment] 2017-07-05 19:27
I'm going to file a new issue, the keys mentioned in https://github.com/jangernert/FeedReader/issues/469#issuecomment-296790832 don't exist in the stable version.
