### ISSUE TITLE
documentation suggestions

### ISSUE THREAD

**Issue by nsheff** [jangernert/FeedReader#686] opened 2018-05-15 20:02 UTC
Just came across FeedReeder and tried to install it. I have a few suggestions:

1. instructions on the web page are wrong. This doesn't work:
```
flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref
error: Can't load uri http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref: Error resolving 'feedreader.xarbit.net': Name or service not known
nsheff@puma:~$ 
```
The server `http://feedreader.xarbit.net/` is down, maybe?

~~2. I installed in following other directions (on GitHub) but how do I actually *run* the software? There is no new app in my menu, command line `feedreader` does not exist... There is no documentation anywhere on how to actually run FeedReader after installing.~~ nevermind on number 2, I just had to restart my computer for some reason.

**Comment by bilelmoussaoui** [comment] 2018-05-15 20:10
Duplicate of https://github.com/jangernert/FeedReader/issues/685

**Closed by bilelmoussaoui** 2018-05-15 20:10 UTC
