### ISSUE TITLE
Feed names are corrupted

### ISSUE THREAD

**Issue by Venemo** [jangernert/FeedReader#502] opened 2017-06-15 14:52 UTC
I'm running `feedreader-2.0.2-1.fc25.x86_64`.

After adding some feeds, the names of previously added feeds become corrupted. For example, `Phoronix` becomes `P`, `Planet GNOME` becomes `Planet GNOM`, etc.

Here is a screenshot of the problem: http://imgur.com/a/1Rfmj

**Comment by bil-elmoussaoui** [comment] 2017-06-15 15:00
Can you please try adding new feeds while running feedreader from terminal (the daemon not the ui)
You can do that by first killing the daemon `pkill feedreader-daemon` and then just type `feedreader-daemon`, after that reopen the UI and try adding some new feeds. Copy & paste the output from the terminal here

**Comment by Venemo** [comment] 2017-06-20 15:52
@bil-elmoussaoui Here it is: https://pastebin.com/EKa6EWiD

Here's what I did:

* Launch feedreader UI
* Create new local RSS account
* In the wizard, select Planet KDE, Planet GNOME and Phoronix
* Wait for sync
* Close UI
* Kill the daemon
* Start the daemon in a terminal
* Start the UI
* Add some feeds

As you can notice in the log, the `Qt Blog` has become `Q` and `Phoronix` has become `Phoroni`.

**Comment by Venemo** [comment] 2017-06-20 15:53
Forgot to mention: I'm running the latest version from the Fedora 25 repo.

If there is anything else I can help you with to debug this issue, let me know!

**Comment by jangernert** [comment] 2017-06-20 19:51
@Venemo I'll try to get to it by the weekend. But I have a lot of things to do right now, so I can't promise.

**Comment by Venemo** [comment] 2017-06-21 10:48
Why this issue was surprising for me is because it shows up basically right away after starting to use the app, so I'm just surprised nobody else noticed it before.

**Comment by jangernert** [comment] 2017-07-09 16:48
Just tried to reproduce the issue by following your list without success:

![screenshot from 2017-07-09 18-46-48](https://user-images.githubusercontent.com/12012494/27995928-125bab1c-64d7-11e7-8c56-e1bc202ae477.png)

Without knowing what causes the issue, I can't fix it.

**Comment by Venemo** [comment] 2017-07-09 17:52
@jangernert Is there any way I could help to investigate what's going on?

**Comment by Venemo** [comment] 2017-07-09 21:12
@jangernert I've just tried with latest master, and the problem is still there.
![screenshot from 2017-07-09 23-12-07](https://user-images.githubusercontent.com/722813/27997604-1ab7c21c-64fc-11e7-86ab-b3144a232893.png)

**Comment by jangernert** [comment] 2017-07-09 21:43
Doesn't help if I can't reproduce it =/
If you already compiled master successfully you could just as well start digging through the code ;)
I don't have tons of time right now to work on FeedReader, but I could help you with debugging and see where things break for you.

**Comment by Sinihopea** [comment] 2017-07-19 23:26
I'm having this same issue. I don't even need to do anything. After I rename any feed to be like "blog.gtk.com" I can just wait and in 15-30 minutes or so and the name becomes corrupt into a "blog.g" or some similar shorter form in real-time as if it's losing characters every time the FeedReader is doing a check on the feed or something.

I suspect the corruption happens byte by byte. I have a Japanese language feed I follow and I've renamed it as such and kana and kanji characters become those square boxes of "unknown byte chars" which happens when the three byte UTF-8 representations are broken.

I was having this issue in Fedora 25 and now that I'm in Fedora 26 the issue is more annoying than ever before since it happens fairly quickly and consistently.
![kuvakaappaus 2017-07-20 02-19-17](https://user-images.githubusercontent.com/1064221/28393855-df1f7b2a-6cf1-11e7-9129-77572e9fdcfb.png)

**Comment by jangernert** [comment] 2017-07-20 12:04
@Sinihopea better start the `feedreader-daemon` from the shell first, so you can see what kind of errors are occurring.

**Comment by jangernert** [comment] 2017-07-20 22:52
can anyone test this commit 96a3fb46dae21c71b45b9ded49bef0f3604885a2 and see if it fixes the bug?
Don't have a lot of time these days =/

**Comment by Venemo** [comment] 2017-07-22 10:52
@jangernert I tested it, the bug is still there :(

**Comment by jangernert** [comment] 2017-07-22 11:23
Did you start out with a fresh account? The altered names would not just magically return to what they once were.

**Comment by Venemo** [comment] 2017-07-22 11:27
@jangernert Yes, I deleted `~/.local/share/feedreader/ and then created a new account.

**Comment by jangernert** [comment] 2017-07-22 11:33
Like I said, I was just looking through the code and found something that *could* cause problems. Since I can't reproduce the issue, I have no idea what actually causes the issue.

**Comment by jangernert** [comment] 2017-07-22 13:02
Btw: you killed the running daemon after compiling and installing master, right? Otherwise the old version is still running ;) just asking to be sure

**Comment by Venemo** [comment] 2017-07-23 10:44
@jangernert Yes, of course I did.

Since both @Sinihopea and myself experience this on Fedora, @jangernert do you also run on Fedora? Perhaps the issue is related to some library (or its Fedora version) that feedreader depends on.

**Comment by Sinihopea** [comment] 2017-07-24 18:24
I came check replies and add that this issue also happens in FlatPak version of FeedReader on Fedora 26. At first I thought it wouldn't be an issue because it worked fine for few days but then is suddenly did it. I removed the Fedora provided version before installing the FlatPak version and I also cleaned up my `~/.local/share/feedreader/ ` and `~/.var/app/org.gnome.FeedReader/data/feedreader` before starting to use it. It has to be something that occurs after a while of using clean install of FeedReader. And so far it's only on Fedora.

![kuvakaappaus 2017-07-24 21-02-24](https://user-images.githubusercontent.com/1064221/28537432-7c0461fc-70b3-11e7-894b-97b5428cafa9.png)

@jangernert Yes, of course I took a look at that first after reading this thread. But I don't see anything that would catch my interest. However in daemon.log it showed some warnings near-by the debug information like this sometimes (this is from the Fedora's packaged FeedReader's daemon.log file):

`
[ INFO  ] daemon: sync started
[ DEBUG ] Ping: https://duckduckgo.com/
[ DEBUG ] Ping: status 200
[ DEBUG ] Ping successfull
[WARNING] dbDaemon: Deleting nonexisting categories
[WARNING] dbDaemon: Deleting articles without feed
[WARNING] dbDaemon: Deleting unsibscribed feeds
[ DEBUG ] getArticles for feed: omgub
[ DEBUG ] getArticles for feed: phoro
[ DEBUG ] getArticles for feed: gnome
[ DEBUG ] getArticles for feed: n
[ DEBUG ] getArticles for feed: linux
[ DEBUG ] getArticles for feed: opera
[ DEBUG ] getArticles for feed: fedor
[ DEBUG ] getArticles for feed: final
[ DEBUG ] getArticles for feed: l
[ DEBUG ] getArticles for feed: 黒
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[WARNING] no valid ID - using URL as ID
[ DEBUG ] getArticles for feed: o
[ DEBUG ] getArticles for feed: thegg
[ DEBUG ] getArticles for feed: blog.
[ DEBUG ] getArticles for feed: apgnation
[ DEBUG ] getArticles for feed: n
[ DEBUG ] getArticles for feed: j
[ DEBUG ] getArticles for feed: fabie
[ DEBUG ] localInterface: 298 articles written
[ DEBUG ] FeedServer: new articles: 1
`

You might want to fix that `unsibscribed` typo if you haven't already, by the way. :)

I can install the FeedReader from sources and run it a little while and when I notice the issue occur, I can post the whole log to Pastebin or something if you wish to take a look at it.

**Comment by jangernert** [comment] 2017-07-25 08:55
@Sinihopea I think the typo is fixed in master.

Yes, I'm also on Fedora. Still Fedora 25 to be exact.

**Comment by Sinihopea** [comment] 2017-07-25 09:55
@jangernert Hah, ok. I'll fetch the latest sources and take a look at it if I see it still there.

And I wrote this before but I need to highlight how this was not a big problem for me in F25. It did occur every now and then and was just few characters but it wasn't a big issue until I upgraded to F26. That's how I ended up in this thread talking about this. I'd strongly encourage you to make a F26 virtual machine or something where you can test this. I can share my OPML file as well if you're interested in replicating conditions as exactly as possible.

**Comment by Venemo** [comment] 2017-07-25 09:57
@jangernert @Sinihopea For me the error appears in after a couple of hours of running latest master FeedReader.

**Comment by Sinihopea** [comment] 2017-07-25 09:59
@Venemo I'm in a middle of testing latest master. Based on past experiences it can occur as early as 30 minutes for me but it can take longer like up to several hours like you pointed out.

**Comment by jangernert** [comment] 2017-07-25 10:15
Okay, I'll try that next time. I only synced 3-4 times without any negative side effects.

**Comment by Venemo** [comment] 2017-07-25 10:35
@jangernert What I did:

* `killall -9 feedreader-daemon`
* `rm -rf ~/.local/share/feedreader`
* start feedreader GUI
* create new Local RSS account
* add the feeds that are shown in my logs
* let the GUI run for a couple of hours

**Comment by Sinihopea** [comment] 2017-07-25 14:17
@Venemo @jangernert I just came to tell that the latest master (or whatever was the master four hours ago) still has this issue. Just a moment ago some of the feeds I added some hours ago lost their names almost completely leaving only one character as the feed title.

**Comment by jangernert** [comment] 2017-07-25 19:56
@Sinihopea I'm pretty much aware of all the places the feed names can get messed up in the code. But thx anyway.
My test-setup is now running almost 3.5h without any issues =/ I even kept the UI running even though that shouldn't affect things at all.

**Comment by Sinihopea** [comment] 2017-08-01 18:36
@jangernert I'd so love to know how to reproduce this issue so that you can see it. I just opened feedreader I compiled from then latest master one week ago and practically all my feed titles are just gone except for the three of them which haven't received any updates last week.

![kuvakaappaus - 2017-08-01 21-34-01](https://user-images.githubusercontent.com/1064221/28840959-564bb51a-7701-11e7-8c88-ccd219d78f69.png)

**Comment by jangernert** [comment] 2017-09-05 00:46
I am on fedora now for about 2 weeks and have been using the local back end ever since. I haven't run into the problem at all.
But since I feeds, categories and tags are now not rewritten every sync any more (added property), this should not happen again.
Feel free to test: deb78aba7918b1620aa2e0882cf504f47ff48e7a

**Comment by Sinihopea** [comment] 2017-09-07 15:44
Ok, I'll put it into a test run later today. Thanks!

**Comment by Venemo** [comment] 2017-09-07 17:32
I've tried latest master a few days ago. It hasn't exhibited this bug yet, but it's otherwise very flaky: it simply does not download any article from some feeds, newly added feeds don't show up until I restart the GUI, it doesn't download icons for feeds, etc. I'll try to rebuild again now to see if it works or not.

**Comment by bil-elmoussaoui** [comment] 2017-09-07 17:39
@Venemo Providing the logs from the daemon/gui would be very helpful

**Comment by Venemo** [comment] 2017-09-07 17:42
@bil-elmoussaoui You mean the terminal output or is there an other kind of log?

**Comment by bil-elmoussaoui** [comment] 2017-09-07 17:57
https://github.com/jangernert/FeedReader/issues/502#issuecomment-308761443

**Comment by Venemo** [comment] 2017-09-07 18:03
@bil-elmoussaoui OK, I opened a separate bug report for that, see #542

**Closed** 2017-09-07 20:22 UTC
Labels: bug

**Comment by twouters** [comment] 2017-10-03 10:10
I'm running master on Archlinux and I'm experiencing this issue.
I have removed `~/.local/share/feedreader` and restarted the daemon and gui. At first the feed names were fine, but the problem returned after a while.
