### ISSUE TITLE
Broken link to flatpak file

### ISSUE THREAD

**Issue by sirredbeard** [jangernert/FeedReader#701] opened 2018-06-09 04:08 UTC
The URL on:

`https://jangernert.github.io/FeedReader/`

provided for the flatpak:

`flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref`

is broken.

Correct commands should be what they are in README.

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.gnome.FeedReader
```

As an aside, is the Feedreader website hosted on GitHub where I could just submit PR's for edits directly? I couldn't find it.

**Comment by bilelmoussaoui** [comment] 2018-06-09 07:30
This is a duplicate of #695. There's already a pending PR here #697. The website is on gh-pages branch. You can take a look at my PR and see if there's anything you think it should be mentioned or not.

**Closed by bilelmoussaoui** 2018-06-09 07:30 UTC
