### ISSUE TITLE
always saying offline 

### ISSUE THREAD

**Issue by elswerky** [jangernert/FeedReader#696] opened 2018-05-24 20:45 UTC
hello 
there is a problem in this app which is it most of the time say that i am offline although i am connected to wifi which is working in all the apps 

but here it keeps saying that i am offline although i press the refresh button 
i am using it on manjaro linux (manjaro deepin)

i connected to it using feedly account

any idea or suggestion ???

also if you can add an option to add more than one account 
for example add feedly account and  tiny tiny rss account at the same time (currently i can connect only to one account ) 

![deepinscreenshot_select-area_20180524224605](https://user-images.githubusercontent.com/26687459/40512868-5f41fd32-5fa4-11e8-8584-ca416ba968e8.png)

**Comment by elswerky** [comment] 2018-05-24 21:05
manjaro version i have is v 2.2 dev  as in screenshot

about multiple account ok i will provide it in another thread



![deepinscreenshot_select-area_20180524230259](https://user-images.githubusercontent.com/26687459/40513698-d1b7f4d2-5fa6-11e8-9fe6-5fa166d350c7.png)

**Comment by bilelmoussaoui** [comment] 2018-05-24 21:08
Can you open the application from the terminal and paste the logs here? 
Also if you can check out using DConf editor the values of `org.gnome.feedreader.feedly` `access-token` and `refresh-token`. 
It might be an issue with the Feedly backend.

**Comment by elswerky** [comment] 2018-05-24 21:17
when i type feedreader in terminal it opens without any log

as in video 

![deepinscreenshot_select-area_20180524231450](https://user-images.githubusercontent.com/26687459/40514174-8af172e2-5fa8-11e8-8d40-d64c2ed21ec1.png)

![deepinscreenshot_select-area_20180524231427](https://user-images.githubusercontent.com/26687459/40514184-93769d7a-5fa8-11e8-9e9d-1db663a6a8bb.png)

![deepinscreenshot_select-area_20180524231724](https://user-images.githubusercontent.com/26687459/40514209-a4f1185a-5fa8-11e8-8eef-3b027cf5e783.png)

**Comment by bilelmoussaoui** [comment] 2018-05-24 21:38
There's nothing on the terminal because there's already an instance of FeedReader running. 

@brendanlong Have you any idea why those tokens disappear on Feedly case? Had a similar issue a long time ago when I was using Feedly.

**Comment by elswerky** [comment] 2018-05-24 21:53
https://pastebin.com/Xkvkg6HX


here is the log of feedreader on terminal

**Comment by bilelmoussaoui** [comment] 2018-05-24 22:10
As expected. The tokens got removed but I have no idea why or how! For now you can try to logout from your current Feedly account and login (you won't lose any data at all)
Anyway it's a duplicate of https://github.com/jangernert/FeedReader/issues/511

**Closed by bilelmoussaoui** 2018-05-24 22:10 UTC

**Comment by elswerky** [comment] 2018-05-24 22:49
thank you for your help and reply @bilelmoussaoui

**Comment by brendanlong** [comment] 2018-05-25 13:49
I'm not sure what's happening. I wonder if Feedly logins just expire after a while?

**Comment by jangernert** [comment] 2018-05-25 14:12
They do expire. That's why there is a timestamp with the expiration date:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/org.gnome.feedreader.feedly.gschema.xml#L35
When the date is reached the refresh token is used to get a new access token from feedly.
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyConnection.vala#L147
