### ISSUE TITLE
Cleaning the database never ends

### ISSUE THREAD

**Issue by zeitrechnen** [jangernert/FeedReader#730] opened 2018-08-06 18:26 UTC
I installed FeedReader and went through the the setup guide. I added two feeds to my local database and then the app crashed. When I opened it again the message "FeedReader is cleaning the database" appeared. After 30 minutes I quit the app. I removed and reinstalled it. But whenever I open the app FeedReader wants to clean the database and never finishes.

Version: 1.6 from Flathub
OS: Pop!_OS 18.04

**Comment by bilelmoussaoui** [comment] 2018-08-06 18:53
How did you install 1.6 from flathub??

**Comment by zeitrechnen** [comment] 2018-08-06 19:55
Yes.

**Comment by bilelmoussaoui** [comment] 2018-08-06 19:56
That's just impossible. The only version we have pushed to flathub is 2.2

**Comment by zeitrechnen** [comment] 2018-08-06 20:43
Sorry, is this a different app? https://flathub.org/apps/details/org.gnome.FeedReader

![bildschirmfoto vom 2018-08-06 22-41-08](https://user-images.githubusercontent.com/1907339/43739901-e82170ba-99c9-11e8-8c2c-47427a1e2d99.png)

**Comment by zeitrechnen** [comment] 2018-08-07 04:46
Weird, seems to be the only app on Flathub with this name. Am I doing something wrong, so that the old version is displayed for me.

**Comment by bilelmoussaoui** [comment] 2018-08-26 08:39
A new flatpak version should be available soon. Please try that and let us know if you still have this issue

**Comment by zeitrechnen** [comment] 2018-08-26 14:02
It works now. Thank you!

**Comment by LBreda** [comment] 2018-09-04 07:35
Same issue on 2.3.0 on flathub

**Comment by LBreda** [comment] 2018-09-07 14:48
Solved by setting "spring-cleaning" to false on gconf org->gnome->feedreader->feedly

**Comment by Wdavery** [comment] 2018-11-06 21:45
Still having this issue. It needs to be reopened.

**Comment by brendanlong** [comment] 2018-11-06 22:11
Reopening since this seems to still be an issue, at least with the Feedly backend.

I've never seen this, but admittedly I clear out of all the app data on a regular basis as part of testing other changes.

@Wdavery  You may want to try our official Flatpak package. We have no control over Solus's packages.

**Comment by brendanlong** [comment] 2018-11-06 22:16
Do any of you happen to have logs from this? The spring cleaning code is surprisingly simple and I don't really see what could be wrong with it. It literally just runs a `VACUUM` in SQLite :\

It's possible the database is locked or something?

**Comment by brendanlong** [comment] 2018-11-06 22:20
Ah I think the issue is that we set a persistent variable when it starts and then if it fails we don't retry?

**Comment by brendanlong** [comment] 2018-11-06 22:49
I was able to reproduce this and also confirmed that pull request #788 fixes it. I'll let you know when it's merged and released.

Thanks for the info @LBreda. I don't think I would have been able to reproduce this without knowing what your workaround was.

**Comment by Wdavery** [comment] 2018-11-06 23:55
Wow, that was a fast fix! I've been struggling with this issue for a while, thanks for looking into it!

**Comment by brendanlong** [comment] 2018-11-09 00:44
I just made a v2.4.1 release in Flathub. It's building now and should be available within an hour or so

**Closed by brendanlong** 2018-11-09 00:44 UTC
Labels: bug
