### ISSUE TITLE
Invalid password bug

### ISSUE THREAD

**Issue by qazip** [jangernert/FeedReader#732] opened 2018-08-22 14:41 UTC
Hello,

I am trying to connect to the nextcloud instance of disroot.org but I am getting an error of "Please enter a valid password".

I know this to be a bug because I am using OCReader on my android in exactly the same way and it works as expected, it connects just fine. 

I am using flatpak's version.

**Comment by jangernert** [comment] 2018-08-22 14:45
duplicate of #724

**Closed by jangernert** 2018-08-22 14:45 UTC
Labels: duplicate
