### ISSUE TITLE
autostart syncing in background

### ISSUE THREAD

**Issue by ghost** [jangernert/FeedReader#898] opened 2019-04-16 06:53 UTC
Hi,
I would like to sync the feeds in background after I login session in my computer.

In the past, I used feedreader-daemon comands. Now It has disappeared. I search some information I should be a new option wih --headles, but

```
$ feedreader --headless
Unknown option --headless
```
I tried wih flatpak package and compile  myself. 
```
...
[   73s] Project name: feedreader
[   73s] Project version: 2.8.2
[   73s] Appending CFLAGS from environment: '-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection'
[   73s] Native C compiler: cc (gcc 8.3.1 "cc (SUSE Linux) 8.3.1 20190226 [gcc-8-branch revision 269204]")
[   73s] Native Vala compiler: valac (valac 0.42.6)
[   73s] Build machine cpu family: x86_64
[   73s] Build machine cpu: x86_64
[   73s] Program afl-fuzz found: YES (/usr/bin/afl-fuzz)
[   73s] Program gtester found: YES (/usr/bin/gtester)
[   73s] Found pkg-config: /usr/bin/pkg-config (0.29.2)
[   73s] Dependency gdk-pixbuf-2.0 found: YES 2.38.1
[   73s] Dependency gee-0.8 found: YES 0.20.1
[   73s] Dependency glib-2.0 found: YES 2.60.0
[   73s] Dependency goa-1.0 found: YES 3.30.2
[   73s] Dependency gstreamer-1.0 found: YES 1.14.4
[   73s] Dependency gstreamer-pbutils-1.0 found: YES 1.14.4
[   73s] Dependency gtk+-3.0 found: YES 3.24.7
[   73s] Dependency gumbo found: YES 0.10.1
[   73s] Dependency json-glib-1.0 found: YES 1.4.4
[   73s] Library curl found: YES
[   73s] Dependency libnotify found: YES 0.7.7
[   73s] Dependency libpeas-1.0 found: YES 1.22.0
[   73s] Dependency libsecret-1 found: YES 0.18.8
[   73s] Dependency libsoup-2.4 found: YES 2.66.0
[   73s] Dependency libxml-2.0 found: YES 2.9.9
[   73s] Library linux found: YES
[   73s] Library posix found: YES
[   73s] Dependency rest-0.7 found: YES 0.8.1
[   73s] Dependency sqlite3 found: YES 3.27.2
[   73s] Dependency webkit2gtk-4.0 found: YES 2.24.0
[   73s] Dependency webkit2gtk-web-extension-4.0 found: YES 2.24.0
[   73s] Dependency unity found: YES 7.1.4
[   73s] Configuring @basename@ using configuration
[   73s] Library webkit2gtk-web-extension-4.0 found: YES
[   73s] Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
[   73s] Program appstream-util found: YES (/usr/bin/appstream-util)
[   73s] Library gd-1.0 found: YES
[   73s] Library gtkimageview found: YES
[   73s] Library htmlclean found: YES
[   73s] Library rss-glib-1.0 found: YES
[   73s] Library m found: YES
[   73s] Message: libUnity support ON
[   73s] Message: Backend Plugin: bazqux ON
[   73s] Message: Backend Plugin: decsync ON
[   73s] Message: Backend Plugin: feedbin ON
[   73s] Message: Backend Plugin: feedhq ON
[   73s] Message: Backend Plugin: feedly ON
[   73s] Message: Backend Plugin: fresh ON
[   73s] Message: Backend Plugin: inoreader ON
[   73s] Message: Backend Plugin: local ON
[   73s] Message: Backend Plugin: oldreader ON
[   73s] Message: Backend Plugin: owncloud ON
[   73s] Message: Backend Plugin: ttrss ON
[   73s] Message: Share Plugin: Browser ON
[   73s] Message: Share Plugin: Email ON
[   73s] Message: Share Plugin: Instapaper ON
[   73s] Message: Share Plugin: Pocket ON
[   73s] Message: Share Plugin: Telegram ON
[   73s] Message: Share Plugin: Twitter ON
[   73s] Message: Share Plugin: Wallabag ON
...
```
I use KDE, is this the reason? Is there anything I can do? 

Thanks anyway!!!

**Comment by brendanlong** [comment] 2019-04-16 16:46
I don't think we support this option right now. If the goal is to run the sync process without the UI, I'd recommend setting up one of the feed server backends (you can do this locally). As much as I hate to recommend it, TT-RSS is relatively easy to setup locally if you install PHP, Apache, and a database: https://git.tt-rss.org/fox/tt-rss/wiki/InstallationNotes

Then the feed server can run continuously in the background without needing to run all of FeedReader.

Note: In my opinion, none of the existing feed servers are particularly easy to setup, and I'm working on my own alternative.

**Comment by JKingweb** [comment] 2019-04-26 19:19
I'm obviously biased, but I like to think [my own feed server](https://thearsse.com/) is easier to set up than most. I, too, am not happy with having to install PHP and its extensions in addition to an HTTP server, though. I'm keen to rewrite it in a language with fewer run-time dependencies. What alternative are you working on, @brendanlong?

**Comment by brendanlong** [comment] 2019-04-26 19:47
I'm working on a Python alternative, although the language isn't particularly important compared to the fact that I want it to be runnable using Docker + Terraform and basically no other setup needed.

**Comment by bilelmoussaoui** [comment] 2019-05-27 19:18
This is somehow a duplicate of #600

**Closed** 2019-05-28 19:19 UTC
Labels: wishlist
