### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by mcg** [jangernert/FeedReader#125] opened 2016-05-24 15:15 UTC
The "features" page highlights, "Don't like clicking? No problem! FeedReader has keyboard-shortcut's for most of it's actions.", but I cannot find any documentation of what shortcuts exist. Is this available somewhere I am missing?

**Comment by bil-elmoussaoui** [comment] 2016-05-24 15:20
We will add this here #30, but you can use F5 to refresh your feeds, use up, down to choose an other article. I will mark this a duplicate of #30

**Closed by bil-elmoussaoui** 2016-05-24 15:20 UTC
