### ISSUE TITLE
plugins/backend/decsync/ is empty

### ISSUE THREAD

**Issue by raczkow** [jangernert/FeedReader#814] opened 2018-12-04 12:57 UTC
When you try to download zip/tar.gz archive with feedreader 2.6.0 (from https://github.com/jangernert/FeedReader/releases and from https://github.com/jangernert/FeedReader/archive/master.zip), you get an empty directory plugins/backend/decsync/ which leads to compilation errors:

```
plugins/backend/decsync/meson.build:6:0: ERROR:  Non-existent build file 'plugins/backend/decsync/libdecsync/src/meson.build'
```

**Comment by brendanlong** [comment] 2018-12-04 14:46
Duplicate of #813 

I'm going to undo this release until I figure out how to make it work.

**Comment by brendanlong** [comment] 2018-12-04 14:47
Actually not exactly a duplicate.

**Comment by brendanlong** [comment] 2018-12-04 15:53
I think our options here are:

 1. Make custom release artifacts that have the submodule code
 2. Inline the submodule, either just by literally copying it or by using a subtree
 3. Remove the submodule and build/install the dependency instead of vendoring it

I'm leaning toward option 2

**Comment by brendanlong** [comment] 2018-12-07 01:50
I just did a new v2.6.1 release which merges all of this stuff into our repo. Can you take a look and see if that works for you?

**Closed by brendanlong** 2018-12-07 01:50 UTC
Labels: bug

**Comment by raczkow** [comment] 2018-12-07 07:52
It's OK now.
