### ISSUE TITLE
Feedreader does not respect gnome-shell notification settings

### ISSUE THREAD

**Issue by senguendk** [jangernert/feedreader#5] opened 2015-09-30 18:09 UTC
I disabled all types/forms of notification for Feedreader from the gnome notification settings, expecting that feedreader to respect these settings and not show notifications any longer.
However, Feedreader continues to show notifications.

**Comment by jangernert** [comment] 2015-09-30 19:47
Please report bugs over at launchpad (https://bugs.launchpad.net/feedreader)
I will not maintain two separate bug-tracker ;)

**Comment by jangernert** [comment] 2015-10-02 16:07
Btw: got fixed in the latest revision (r549).
But no idea how to close this ticket here on github :P

**Comment by aleksandar-todorovic** [comment] 2015-10-03 14:48
@jangernert Done!

**Closed** 2015-10-03 14:48 UTC
Labels: invalid

**Comment by fedelibre** [comment] 2015-11-14 08:40
Since which version of feedreader [r549](http://bazaar.launchpad.net/~eviltwin1/feedreader/master/revision/549) is present? I'm experiencing this problem on feedreader version 1.2.1 in Fedora23.

**Comment by fedelibre** [comment] 2015-11-14 08:43
Ok, found it on the changelog of the [website](http://jangernert.github.io/feedreader/). It's in 1.4.
BTW, a release date close to the version number would be helpful.
Thanks

**Comment by fedelibre** [comment] 2017-03-13 12:50
@jangernert It seems that this bug is present again on version 2.0.2 (I'm using Fedora 25 package)

**Comment by fedelibre** [comment] 2017-03-24 12:29
@jangernert I've reported it on launchpad as [bug 1675757](https://bugs.launchpad.net/feedreader/+bug/1675757)

**Comment by jangernert** [comment] 2017-03-24 14:55
probably just have to update the name of the desktop file in this line here
https://github.com/jangernert/FeedReader/blob/master/src/Notification.vala#L68
Maybe I'll have time to do it tonight. But a pull request would be nice as well. 
Just update `feedreader` to `org.gnome.FeedReader`

**Comment by bil-elmoussaoui** [comment] 2017-03-24 15:00
@jangernert Done =)

**Comment by jangernert** [comment] 2017-03-24 18:34
Have you tested if it fixes the behaviour?

**Comment by fedelibre** [comment] 2017-03-26 14:34
@jangernert I've compiled from master and since yesterday I've been testing if the fix was effective. At first I thought it was not fixed, but today I would say it's fixed. Perhaps I needed to restart the session. I can confirm my final thought in the coming days

**Comment by fedelibre** [comment] 2017-03-27 16:02
@jangernert I confirm that it's fixed. Thanks
