### ISSUE TITLE
Unicode character problem, themes, fonts

### ISSUE THREAD

**Issue by Narga** [jangernert/FeedReader#476] opened 2017-05-09 08:45 UTC
I've tried FeedReader with my hosted Tiny Tiny RSS but  I found the font problem with Unicode characters in the title and item list.
![screenshot_2017-05-09_15-42-05](https://cloud.githubusercontent.com/assets/212624/25842475/56824c12-34ce-11e7-87be-d0a7c83c8e87.png)
It's still displayed correctly in item's content.
I looked around for the fonts and  article view settings but I'm not found any information about them.
I guest the problem is the font wasn't support Unicode characters as well. How can I change it and how can I edit the article view theme.

**Comment by jangernert** [comment] 2017-05-09 09:01
If you post the url of the feed I can take a look at it. But I can't promise to fix it, since I can't read or speak Vietnamese (at least that's what I think it is, right?)

**Comment by Narga** [comment] 2017-05-09 09:04
Hi, it's here
The feed url: http://feeds.narga.net/mrnarga
The url to to first item: https://www.narga.org/2017/03/truong-thanh-trach-nhiem/

**Comment by jangernert** [comment] 2017-05-11 20:08
I was just about to see what's wrong here when:

![screenshot from 2017-05-11 22-00-22](https://cloud.githubusercontent.com/assets/12012494/25969586/be19c1ca-3695-11e7-8287-6efe627f2ffd.png)

What version are you using?

**Comment by Narga** [comment] 2017-05-12 08:30
I'm facing this problem both on 2.0.2 and git versions.. The item's content is still displaying correctly but the title and item list are not.
Could you tell me the font properties of the titles, I'm guessing my system is lack of that font or the font was broken.

**Comment by jangernert** [comment] 2017-05-12 09:19
Did you reset your account after switching to git master? If not the old corrupted data will be used with the new version (depending on when you made the switch, because I recently bumped the version of the db scheme).
Also which back-end are you using?
I don't think it's a missing font, since the title and the text in the article-view are both rendered by webkit and should use the same font as far as I can remember.

**Comment by Narga** [comment] 2017-05-12 17:08
I had removed feedreader completely with pacman -Rscn then deleted the `~/.local/share/feedreader/` to remove the database.
I installed feedreader 2.0.2 then re-add the source from tiny tiny rss and feedly, I still got this problem, the content is perfect but the title is broken with junk characters.
I repeat the first step again then installed the git version, it's the same.
I ran `feedreader` via terminal but I'm not find any error message about that.

**Comment by jangernert** [comment] 2017-05-12 17:25
You are aware that there is a process called `feedreader-daemon` that does all the work getting and writing the articles to the database?
If you install a new version of feedreader you also have to kill the running instance of the daemon. Otherwise the old instance of the daemon will keep running.
I also tested with tt-rss. That sadly dismisses another possible clue where things could have gone wrong =/

**Comment by Narga** [comment] 2017-05-12 18:03
Aaahhh, I've tried again after run `$ killall feedreader-daemon`, I still got the same character problem with only title and item list.

**Comment by jangernert** [comment] 2017-05-12 18:32
So the problem is most likely here:
https://github.com/jangernert/FeedReader/blob/master/src/UtilsDaemon.vala#L43
https://github.com/jangernert/FeedReader/blob/master/src/UtilsDaemon.vala#L66

This basically calls libVilistextum that should fix all the malformed characters you sometimes get from the WWW. For some reason that seems not to work on your machine.
https://github.com/jangernert/FeedReader/tree/master/libVilistextum
You could try to comment both of these lines out and rebuild FeedReader, then delete your database and restart the daemon. If it works after that the issue is somewhere in libVilistextum =/

**Comment by jangernert** [comment] 2017-05-12 18:47
Btw: I noticed there have been some updates and fixes in the git repository of vilistextum since the last release in 2006. I guess I'll start backporting those changes. Maybe it'll even help in this situation.

**Comment by jangernert** [comment] 2017-05-12 19:59
You could also take a look at the database and check if the strings are already messed up in there.
There are lots of tools out there to view sqlite database files.
![screenshot from 2017-05-12 21-58-28](https://cloud.githubusercontent.com/assets/12012494/26014737/382dc6a0-375e-11e7-85c0-a30f28d62ff9.png)

**Comment by Narga** [comment] 2017-05-13 05:14
Thanks, when I check the title colume in the database, I had found the characters was messed exactly as I've viewed in the `feedreader`.
What am I need to do now for fix it?

**Comment by Narga** [comment] 2017-05-13 07:27
When I had rebuilt `feedreader` with 2 lines commented in `UtilsDaemon.vala` I found the error
`: Can't translate pathname 'usr/share/FeedReader/GrabberConfig/pérotin.com.txt' to UTF-8` at the end of process and ` Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()` in the command running.

**Comment by jangernert** [comment] 2017-05-13 13:44
I guess with the `UTF8fix`-function removed you see some weird symbols in the article-list?
That sounds to me that the title is already malformed when FeedReader gets it.
Could you please update the code again and try the local back-end?
Sorry for all the inconvenience. But I hope this will shed some light on to the situation.

**Comment by Narga** [comment] 2017-05-13 16:59
I've rebuilt `feedreader-git` with your lastest updates but  the problem is still exist. I can't add news feed source because the plus button is not respond for me when click on. So I must using other feed resources instead local rss.
I'm wonder why your app running correctly on your system. Do I missing dependencies? I built it from Arch Linux's AUR.

**Comment by Narga** [comment] 2017-05-13 17:02
Give me more time, I'll double  check my system font settings.

**Comment by Narga** [comment] 2017-05-14 09:24
My font configuration hasn't any problem and conflicted issues.
With the newest build of `feedreader`, every unicode characters has disappeared in the title, content and item list. I only see the latin character 😺

**Comment by bilelmoussaoui** [comment] 2019-02-10 13:37
Do you still have this issue with the latest release? You can get it from Flathub and let us know if you can still reproduce the issue. We have changed a lot of stuff and this issue might have been fixed during those changes

**Comment by brendanlong** [comment] 2019-02-13 15:16
To clarify, this issue was with a library we were using called libvilistextum which tried to clean up feed titles if they contained invalid characters, but it didn't work correctly with some character encodings. We completely removed that library and replaced with it with something else. This should be fixed, but please let us know if you still see this problem on the latest version.

**Comment by JoseVacas** [comment] 2019-02-20 09:34
Same problems on headers news

![imagen](https://user-images.githubusercontent.com/3788803/53081371-0497be80-34fb-11e9-8972-4f26305ed820.png)

**Comment by brendanlong** [comment] 2019-02-20 14:31
Thanks for the information. I'll try to look into this when I can.

Can you share the feed URL for ALT1040?

**Comment by brendanlong** [comment] 2019-02-20 14:45
@JoseVacas Can you share the feed URL for ALT1040, and also let me know what your locale is set to?

If you just run `locale` in a terminal it should give you info like this:

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

(Our old libvilistextum code didn't work right if your locale wasn't UTF-8, so one thing I want to check if is there's another issue like that still in our code)

**Comment by brendanlong** [comment] 2019-02-20 17:38
@JoseVacas Also, can you confirm that you're using the latest FeedReader version (v2.8.2)?

**Comment by brendanlong** [comment] 2019-02-20 17:41
Ah the RSS feed is http://alt1040.com/feed and I can reproduce the problem:

https://guides.github.com/features/mastering-markdown/
![screenshot from 2019-02-20 12-41-10](https://user-images.githubusercontent.com/1447206/53112253-d3c08500-350c-11e9-905c-f663403af572.png)

**Comment by brendanlong** [comment] 2019-02-20 18:39
See #886. This should be fixed when we do our next release.

**Closed** 2019-02-20 18:39 UTC
Labels: bug

**Comment by Narga** [comment] 2019-02-21 08:39
@bilelmoussaoui sorry I'm late, thanks for your works, I've tried the newest version and found the Unicode characters are display correctly but, the app always crash after several minutes. I ran it from the commandline then has:
`(feedreader:32102): GLib-DEBUG: 15:11:45.284: posix_spawn avoided (fd close requested) 
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

    #1  <unknown>   in 'g_thread_join'
        at /usr/lib/libglib-2.0.so.0
    #2  <unknown>   in 'g_closure_invoke'
        at /usr/lib/libgobject-2.0.so.0
    #3  <unknown>   in 'g_signal_emit_valist'
        at /usr/lib/libgobject-2.0.so.0
    #4  <unknown>   in 'g_signal_emit'
        at /usr/lib/libgobject-2.0.so.0
    #5  <unknown>   in 'g_main_context_dispatch'
        at /usr/lib/libglib-2.0.so.0
    #6  <unknown>   in 'g_main_context_iteration'
        at /usr/lib/libglib-2.0.so.0
    #7  <unknown>   in 'g_application_run'
        at /usr/lib/libgio-2.0.so.0
    #8  <unknown>   in 'feed_reader_main_main'
        at feedreader
    #9  <unknown>   in '__libc_start_main'
        at 
    #10  <unknown>   in '_start'
        at feedreader
`

**Comment by brendanlong** [comment] 2019-02-21 12:07
I created #889 to track this crash. Having a separate issue makes it much easier for me to keep track of things.
