### ISSUE TITLE
Support for "atom" type feeds?

### ISSUE THREAD

**Issue by Gert-dev** [jangernert/FeedReader#324] opened 2017-01-17 18:17 UTC
Hello

I was wondering if atom feeds are currently supported or on the roadmap.

I imported a larger of feeds via an OPML file (in 2.0 beta1) and it succeeds, but most of my feeds are missing and seem to have been skipped. At first I thought this was just a bug because it's a beta, but looking at the OPML file, the skipped feeds appear to all have a `type="atom"` whilst the working ones have `type="rss"`.

I've also attempted to manually add such a feed afterwards. It is added, but no items are fetched, the main view just claims no items were found.

Thanks in advance

**Comment by jangernert** [comment] 2017-01-17 19:28
I use libmrss to parse the feeds. So all these formats are supported:

    RSS 0.91 - http://my.netscape.com/publish/formats/rss-spec-0.91.html
    RSS 0.92 - http://backend.userland.com/rss092
    RSS 1.0 - http://web.resource.org/rss/1.0/
    RSS 2.0 - http://www.rssboard.org/rss-specification
    ATOM 0.3 - http://www.mnot.net/drafts/draft-nottingham-atom-format-02.html
    ATOM 1.0 - http://tools.ietf.org/html/rfc4287
https://www.autistici.org/bakunin/libmrss/doc/

**Comment by Gert-dev** [comment] 2017-01-17 20:43
I see. I tried adding it manually again and now, it suddenly does synchronize the atom feed. Since that's ruled out, only an OPML import issue seems to remain. About half of my OPML file is effectively skipped during import, the skipped feeds are always the same ones.

I've reduced the OPML file to one with two items, where one is always skipped so you can test if it's actually a bug or something I'm doing wrong:

```xml
<?xml version="1.0"?>
<opml version="1.0">
  <head>
    <title>Feed List Export</title>
  </head>
  <body>
    <outline title="My Feeds" text="My Feeds" description="My Feeds" type="folder">
      <outline title="GNOME Desktop Environment" text="GNOME Desktop Environment" description="GNOME Desktop Environment" type="atom" xmlUrl="https://www.reddit.com/r/gnome/.rss?limit=200" htmlUrl="https://www.reddit.com/r/gnome/?limit=200"/>
      <outline title="Gaming On Linux" text="Gaming On Linux" description="Gaming On Linux" type="rss" xmlUrl="http://www.gamingonlinux.com/article_rss.php" htmlUrl="http://www.gamingonlinux.com/"/>
    </outline>
  </body>
</opml>
```

The GamingOnLinux (RSS) feed is correctly added, but the reddit (Atom) feed is skipped and never imported.

**Comment by jangernert** [comment] 2017-01-17 21:19
The OPML-parser could definitely be faulty, since I wrote it :P 
Will test it with your OPML and try to fix it.

**Comment by Gert-dev** [comment] 2017-01-18 16:26
Thanks for the quick fix, that seems to have fixed it.

I'm now running into another problem that I did not have before, namely that all my feed names and the contents of feed articles contain garbled Unicode characters, e.g. `Gaming On Linux LL `. However, I don't recall this happening in 2.0 beta 1, so that may be another issue entirely.

![screenshot](https://cloud.githubusercontent.com/assets/24809863/22072595/1f8825c4-dda3-11e6-9a1a-19aa5e728230.png)

**Comment by jangernert** [comment] 2017-01-18 17:40
Can you test if reverting commit 25b38721e396aa473fb86430efa3fb6d230bae64 fixes this for you?
I am currently not at home and can't test it myself.

**Comment by Gert-dev** [comment] 2017-01-18 18:11
Reverting the commit itself did not work as it generated conflicts, but I did try to go back to 2.0 beta 1 and applying the fix for the Atom feeds. That seemed to get everything in working order and confirms it is something that was added onto master later on (possibly the referenced commit).

**Comment by jangernert** [comment] 2017-01-18 22:19
Any other feeds that have this issue? I can't reproduce it with latest code, local-backend and this [feed](https://www.gamingonlinux.com/article_rss.php).

It definitely has to be one of the two commits:
1d3f1d3e5a7ca91af54a7eb70577e38b7917ef99
25b38721e396aa473fb86430efa3fb6d230bae64

Maybe you could revert the second commit manually? it's just 8 lines that changed in 2 files of libvilistextum.
Before doing this you should try if this commit of latest master fixes your issues.
03f867fceb85464a67c8ce750fd17ded4b737acf
I forgot to reset the size-counter of the OUTPUT-buffer when freeing the memory I introduced in 1d3f1d3e5a7ca91af54a7eb70577e38b7917ef99. This could have lead to the buffer growing way too big =/

**Comment by Gert-dev** [comment] 2017-01-19 15:43
All of the feeds, including the one you tested, give the same issue here.

I haven't completely done all the steps you posted yet (will create a new post when I have), but below you'll find a couple of things I'm noticing with the latest master.

I think it's easiest if I describe the steps I'm taking to reach this state along with what is going wrong:

1. I open up FeedReader with a clean slate and try to import my OPML file. The loading spinner at the bottom shows up.
2. The loading spinner stops and most of my feeds are now present in the folders they are in.
    * I notice that OPML feeds that are in no subcategory, i.e. aren't nested in another `outline` tag, are skipped during import.
    * The names of the feeds are garbled again just like before. This rules out commit 03f867fceb85464a67c8ce750fd17ded4b737acf fixing it.
3. I try to manually add a missing top level feed by entering its URL and selecting no category.
4. The item ends up in an automatically created "Uncategorised" folder. I'd rather have them on the top level, but this is no big deal. The loading spinner at the top now starts. I'm not sure what that is doing now. Is it fetching the feed? It didn't fetch the feeds during the import either, so I'm not sure.
5. I try adding another top level feed without a category. Now weird things start happening: the loading spinner at the top is still running from the previous feed and at first, my action seems to have no effect. The feed is not added.
6. After a couple of seconds, the first top level feed I added in "Uncategorised" suddenly gets the name from another feed that was imported from the OPML and is seemingly unrelated. The name is also garbled, not garbled as in Unicode garbled, but letters in various adjacent words are effictively switched around.
7. I try importing the second top level feed for the second time and now it replaces the first (garbled) feed in the "Uncategorised" folder. The first top level feed I added now seems effectively gone.
8. The loading spinner at the top is still spinning even though it's been a couple of minutes.
9. I restart FeedReader. The loading spinner is not spinning anymore, but the state of my feeds is still the same. This seems to rule out some sort of visual out-of-sync issue.

**Comment by Gert-dev** [comment] 2017-01-19 15:53
I just tried rolling back 1d3f1d3 and that did fix the unicode garbling issue.

**Comment by jangernert** [comment] 2017-01-19 16:25
Okay let's focus on the Unicode stuff for a sec :D
Did latest master fix the Unicode issue for you as well?

**Comment by jangernert** [comment] 2017-01-19 17:34
Did you kill the running instance of feedreader-daemon after updating to the latest master?
If not the old binary was still running =/
The missing toplevel-feeds is probably another bug in the opml-parser (can you upload your opml somewhere, so I can use it as a reference?).
Everything without a category landing in uncategorized is by design. You have the option to list all your feeds without any categories though ;)

**Comment by Gert-dev** [comment] 2017-01-19 18:30
To answer your question: Yes, I did kill the feedreader-daemon every time.

For the top level feeds bug, here is an example, it is just the same as before, but without an additional wrapping `outline` tag that describes the category.

```xml
<?xml version="1.0"?>
<opml version="1.0">
  <head>
    <title>Feed List Export</title>
  </head>
  <body>
    <outline title="GNOME Desktop Environment" text="GNOME Desktop Environment" description="GNOME Desktop Environment" type="atom" xmlUrl="https://www.reddit.com/r/gnome/.rss?limit=200" htmlUrl="https://www.reddit.com/r/gnome/?limit=200"/>
    <outline title="Gaming On Linux" text="Gaming On Linux" description="Gaming On Linux" type="rss" xmlUrl="http://www.gamingonlinux.com/article_rss.php" htmlUrl="http://www.gamingonlinux.com/"/>
  </body>
</opml>
```

Having the uncategorized option seems OK to me, I can adapt to that :-).

**Comment by jangernert** [comment] 2017-01-19 20:17
I'll look at the  OPML later.
Btw: the new libvilistextum-code will only affect newly fetched articles. Once the html has been parsed and written to the db (with the encoding issues) it will stay that way.
Can you give latest master another try?
If that doesn't work I could give you my test-environment for libVilistextum and you can try to figure out what is going wrong inside the OUTPUT-buffer. Would be cool if you could help me with the issue :)

**Comment by Gert-dev** [comment] 2017-01-20 20:34
The latest master also doesn't seem to fix it :-(. I could take a look at libVilistextum, but looking at the code, I have no idea what it is used for? If I understood correctly, FeedReader's GUI is a Vala app, but what is the C side doing? Parsing feed structure or even article contents?

**Comment by jangernert** [comment] 2017-01-20 23:42
It's a modified version of this programm http://bhaak.net/vilistextum/index.html
I use it to parse all the text I get from the web. For one to generate the preview-texts from the html-documents. And to fix all the wonky encoding from all over the www.

Here is a small test-setup for the lib with a makefile
[test.zip](https://github.com/jangernert/FeedReader/files/720741/test.zip)
Just look at test.vala

**Comment by jangernert** [comment] 2017-01-21 12:02
The issue with the top-level-feeds not showing up should be fixed. The feeds were actually imported but the wrong category-id was assigned. So they didn't show up.

**Comment by jangernert** [comment] 2017-01-22 23:42
Since this specific issue is fixed, could you please open up another bug for the libVilistextum-thing?

**Closed by jangernert** 2017-01-22 23:42 UTC
Labels: bug
