### ISSUE TITLE
Quit doesn't quit

### ISSUE THREAD

**Issue by hfiguiere** [jangernert/FeedReader#880] opened 2019-02-16 13:10 UTC
* start feedreader
* go to the application menu and select quit (the one at the top that the shell handles)

Expected

* feedreader terminates

Observed

* the window is gone
* feedreader still run in the background

**Comment by hfiguiere** [comment] 2019-02-16 13:11
I believe closing the main window should also quit the application.

**Comment by brendanlong** [comment] 2019-02-16 17:08
Duplicate of #694

**Closed by brendanlong** 2019-02-16 17:08 UTC
