### ISSUE TITLE
unread tab - read items should disappear on refresh

### ISSUE THREAD

**Issue by Justinzobel** [jangernert/FeedReader#43] opened 2016-01-27 22:42 UTC
Selected unread tab at top, read my articles, refreshed but read articles remain.

**Comment by jangernert** [comment] 2016-01-28 08:20
What exactly do you mean? In the unread tab the articles should disappear as soon as they are read and not selected anymore. So by the time you hit refresh there should be only one read article left in the list, the one that is selected (not gonna remove the selected article, because the user may still be reading).

**Comment by Justinzobel** [comment] 2016-01-28 09:09
More than one article are left there after being read, so they are not
disappearing correctly.

**Comment by jangernert** [comment] 2016-01-28 09:21
What backend are you using? Can you exactly explain how to reliably reproduce the issue?

**Comment by Justinzobel** [comment] 2016-01-28 21:11
Using the Feedly backend, I just tried again today and can't reproduce. Will keep monitoring it though.

**Comment by Justinzobel** [comment] 2016-01-29 04:43
![screenshot from 2016-01-29 15-12-22](https://cloud.githubusercontent.com/assets/1370117/12667386/cb677d5c-c69a-11e5-8e2d-dcd816c1b284.png)

**Comment by jangernert** [comment] 2016-01-29 08:55
It's not that I couldn't imagine what the issue would look like. It's just that I don't know what's wrong, if I can't reproduce the issue myself and investigate =/

**Comment by Justinzobel** [comment] 2016-01-29 23:41
Any debug logs or logs in general I can provide that'd help?

**Comment by jangernert** [comment] 2016-01-30 11:13
First of all: how did you mark the articles as read? Did you click on them in the list, did you click the blue circle to mark them as read or did you read them on the feedly website?
Did you try if the bug is still present in master? (fixed a bunch of articleList related bugs there)
If the bug is still present in master, I can add some specific debug messages for you ;)

**Comment by Justinzobel** [comment] 2016-01-30 22:23
I don't read them in Feedly, only in Feedreader, I just read them by
clicking on them (not the blue circle) and then clicking on the next. I'll
try master today and report back.

**Comment by jangernert** [comment] 2016-02-26 14:39
any news on this issue?

**Comment by Justinzobel** [comment] 2016-02-26 21:44
Sorry got completely distracted, have just grabbed master and installed, will test over the next day or so and report back.

**Comment by Justinzobel** [comment] 2016-02-29 01:11
Still happening in master branch.

**Comment by jangernert** [comment] 2016-03-03 00:10
Hmmm
can you take a look at the database and see if the articles get correctly marked as read or if there is something weird with the ids? The db is located at HOME/.local/feedreader/data
I use a firefox addon to browse the db =)

**Comment by jangernert** [comment] 2016-03-03 12:42
And if that also does not shed any light on the issue, could you export your feeds and give them to me? Maybe then I can reproduce your issue =/

**Comment by jangernert** [comment] 2016-05-02 15:53
Anything new here?

**Comment by jangernert** [comment] 2016-07-26 22:46
Just had a small chat with justin on g+. Seems like the issue is resolved in master :)

**Closed by jangernert** 2016-07-26 22:46 UTC
Labels: bug
